// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: tx.proto

package contract

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Required by plugin.proto
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type: The type of the transaction like 'send' or 'stake'
	MessageType string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"messageType"` // @gotags: json:"messageType"
	// msg: The actual transaction message payload, which is encapsulated in a generic message format
	Msg *anypb.Any `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// signature: The cryptographic signature used to verify the authenticity of the transaction
	Signature *Signature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// created_height: The height when the transaction was created - allows 'safe pruning'
	CreatedHeight uint64 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	// time: The timestamp when the transaction was created - used as temporal entropy to prevent hash collisions in txs
	Time uint64 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	// fee: The fee associated with processing the transaction
	Fee uint64 `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	// memo: An optional message or note attached to the transaction
	Memo string `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	// network_id: The identity of the network the transaction is intended for
	NetworkId uint64 `protobuf:"varint,8,opt,name=network_id,json=networkId,proto3" json:"networkID"` // @gotags: json:"networkID"
	// chain_id: The identity of the committee the transaction is intended for
	ChainId uint64 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chainID"` // @gotags: json:"chainID"
	// nonce: The sender's protocol replay-protection nonce
	Nonce         uint64 `protobuf:"varint,10,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Transaction) GetMsg() *any1.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Transaction) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Transaction) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// MessageSend is a standard transfer transaction, taking tokens from the sender and transferring
// them to the recipient
type MessageSend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from_address: is the sender of the funds
	FromAddress []byte `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"fromAddress"` // @gotags: json:"fromAddress"
	// to_address: is the recipient of the funds
	ToAddress []byte `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"toAddress"` // @gotags: json:"toAddress"
	// amount: is the amount of tokens in micro-denomination (uCNPY)
	Amount        uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeParams) Reset() {
	*x = FeeParams{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeParams) ProtoMessage() {}

func (x *FeeParams) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeParams.ProtoReflect.Descriptor instead.
func (*FeeParams) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *FeeParams) GetSendFee() uint64 {
	if x != nil {
		return x.SendFee
	}
	return 0
}

func (x *FeeParams) GetCreateMarketFee() uint64 {
	if x != nil {
		return x.CreateMarketFee
	}
	return 0
}

func (x *FeeParams) GetSubmitPredictionFee() uint64 {
	if x != nil {
		return x.SubmitPredictionFee
	}
	return 0
}

func (x *FeeParams) GetResolveMarketFee() uint64 {
	if x != nil {
		return x.ResolveMarketFee
	}
	return 0
}

func (x *FeeParams) GetClaimWinningsFee() uint64 {
	if x != nil {
		return x.ClaimWinningsFee
	}
	return 0
}

// ADLMSR state objects (0x10-0x14)
type MarketState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	ExpiryTime          uint64                 `protobuf:"varint,2,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`
	QYes                uint64                 `protobuf:"varint,3,opt,name=q_yes,json=qYes,proto3" json:"q_yes,omitempty"`
	QNo                 uint64                 `protobuf:"varint,4,opt,name=q_no,json=qNo,proto3" json:"q_no,omitempty"`
	BEff                uint64                 `protobuf:"varint,5,opt,name=b_eff,json=bEff,proto3" json:"b_eff,omitempty"`
	Creator             []byte                 `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	ClaimedCount        uint64                 `protobuf:"varint,7,opt,name=claimed_count,json=claimedCount,proto3" json:"claimed_count,omitempty"`
	TotalPositions      uint64                 `protobuf:"varint,8,opt,name=total_positions,json=totalPositions,proto3" json:"total_positions,omitempty"`
	OpenTime            uint64                 `protobuf:"varint,9,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	ElevatedRisk        bool                   `protobuf:"varint,10,opt,name=elevated_risk,json=elevatedRisk,proto3" json:"elevated_risk,omitempty"`
	FinalizedPoolAmount uint64                 `protobuf:"varint,11,opt,name=finalized_pool_amount,json=finalizedPoolAmount,proto3" json:"finalized_pool_amount,omitempty"`
	Question            string                 `protobuf:"bytes,12,opt,name=question,proto3" json:"question,omitempty"`
	Rules               string                 `protobuf:"bytes,13,opt,name=rules,proto3" json:"rules,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MarketState) Reset() {
	*x = MarketState{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketState) ProtoMessage() {}

func (x *MarketState) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketState.ProtoReflect.Descriptor instead.
func (*MarketState) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MarketState) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MarketState) GetExpiryTime() uint64 {
	if x != nil {
		return x.ExpiryTime
	}
	return 0
}

func (x *MarketState) GetQYes() uint64 {
	if x != nil {
		return x.QYes
	}
	return 0
}

func (x *MarketState) GetQNo() uint64 {
	if x != nil {
		return x.QNo
	}
	return 0
}

func (x *MarketState) GetBEff() uint64 {
	if x != nil {
		return x.BEff
	}
	return 0
}

func (x *MarketState) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *MarketState) GetClaimedCount() uint64 {
	if x != nil {
		return x.ClaimedCount
	}
	return 0
}

func (x *MarketState) GetTotalPositions() uint64 {
	if x != nil {
		return x.TotalPositions
	}
	return 0
}

func (x *MarketState) GetOpenTime() uint64 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

func (x *MarketState) GetElevatedRisk() bool {
	if x != nil {
		return x.ElevatedRisk
	}
	return false
}

func (x *MarketState) GetFinalizedPoolAmount() uint64 {
	if x != nil {
		return x.FinalizedPoolAmount
	}
	return 0
}

func (x *MarketState) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *MarketState) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

type PositionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharesYes     uint64                 `protobuf:"varint,1,opt,name=shares_yes,json=sharesYes,proto3" json:"shares_yes,omitempty"`
	SharesNo      uint64                 `protobuf:"varint,2,opt,name=shares_no,json=sharesNo,proto3" json:"shares_no,omitempty"`
	CostPaid      uint64                 `protobuf:"varint,3,opt,name=cost_paid,json=costPaid,proto3" json:"cost_paid,omitempty"`
	Claimed       bool                   `protobuf:"varint,4,opt,name=claimed,proto3" json:"claimed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionState) Reset() {
	*x = PositionState{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionState) ProtoMessage() {}

func (x *PositionState) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionState.ProtoReflect.Descriptor instead.
func (*PositionState) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *PositionState) GetSharesYes() uint64 {
	if x != nil {
		return x.SharesYes
	}
	return 0
}

func (x *PositionState) GetSharesNo() uint64 {
	if x != nil {
		return x.SharesNo
	}
	return 0
}

func (x *PositionState) GetCostPaid() uint64 {
	if x != nil {
		return x.CostPaid
	}
	return 0
}

func (x *PositionState) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

type OutcomeState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WinningOutcome bool                   `protobuf:"varint,1,opt,name=winning_outcome,json=winningOutcome,proto3" json:"winning_outcome,omitempty"`
	ResolvedAt     uint64                 `protobuf:"varint,2,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutcomeState) Reset() {
	*x = OutcomeState{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutcomeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutcomeState) ProtoMessage() {}

func (x *OutcomeState) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutcomeState.ProtoReflect.Descriptor instead.
func (*OutcomeState) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *OutcomeState) GetWinningOutcome() bool {
	if x != nil {
		return x.WinningOutcome
	}
	return false
}

func (x *OutcomeState) GetResolvedAt() uint64 {
	if x != nil {
		return x.ResolvedAt
	}
	return 0
}

type TreasuryReserve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockedReserve uint64                 `protobuf:"varint,1,opt,name=locked_reserve,json=lockedReserve,proto3" json:"locked_reserve,omitempty"`
	CreatorBond   uint64                 `protobuf:"varint,2,opt,name=creator_bond,json=creatorBond,proto3" json:"creator_bond,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreasuryReserve) Reset() {
	*x = TreasuryReserve{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreasuryReserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreasuryReserve) ProtoMessage() {}

func (x *TreasuryReserve) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreasuryReserve.ProtoReflect.Descriptor instead.
func (*TreasuryReserve) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *TreasuryReserve) GetLockedReserve() uint64 {
	if x != nil {
		return x.LockedReserve
	}
	return 0
}

func (x *TreasuryReserve) GetCreatorBond() uint64 {
	if x != nil {
		return x.CreatorBond
	}
	return 0
}

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\xb9\x02\n" +
	"\vTransaction\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12&\n" +
	"\x03msg\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03msg\x12.\n" +
	"\tsignature\x18\x03 \x01(\v2\x10.types.SignatureR\tsignature\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x04R\x03fee\x12\x12\n" +
	"\x04memo\x18\a \x01(\tR\x04memo\x12\x1d\n" +
	"\n" +
	"network_id\x18\b \x01(\x04R\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\x12\x14\n" +
	"\x05nonce\x18\n" +
	" \x01(\x04R\x05nonce\"g\n" +
	"\vMessageSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\fR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\fR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"&\n" +
	"\tFeeParams\x12\x19\n" +
	"\bsend_fee\x18\x01 \x01(\x04R\asendFee\"H\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"y\n" +
	"\rMessageReward\x12#\n" +
	"\radmin_address\x18\x01 \x01(\fR\fadminAddress\x12+\n" +
	"\x11recipient_address\x18\x02 \x01(\fR\x10recipientAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"{\n" +
	"\rMessageFaucet\x12%\n" +
	"\x0esigner_address\x18\x01 \x01(\fR\rsignerAddress\x12+\n" +
	"\x11recipient_address\x18\x02 \x01(\fR\x10recipientAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amountB3Z1github.com/canopy-network/go-plugin-test/contractb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_tx_proto_goTypes = []any{
	(*Signature)(nil),                   // 0: types.Signature
	(*Transaction)(nil),                 // 1: types.Transaction
	(*FeeParams)(nil),                   // 2: types.FeeParams
	(*MarketState)(nil),                 // 3: types.MarketState
	(*PositionState)(nil),               // 4: types.PositionState
	(*OutcomeState)(nil),                // 5: types.OutcomeState
	(*TreasuryReserve)(nil),             // 6: types.TreasuryReserve
	(*ResolverState)(nil),               // 7: types.ResolverState
	(*ResolverRecord)(nil),              // 8: types.ResolverRecord
	(*ProposalRecord)(nil),              // 9: types.ProposalRecord
	(*DisputeRecord)(nil),               // 10: types.DisputeRecord
	(*VoteCommit)(nil),                  // 11: types.VoteCommit
	(*VoteReveal)(nil),                  // 12: types.VoteReveal
	(*SlashRecord)(nil),                 // 13: types.SlashRecord
	(*PanelEntropyAccum)(nil),           // 14: types.PanelEntropyAccum
	(*MessageSend)(nil),                 // 15: types.MessageSend
	(*MessageCreateMarket)(nil),         // 16: types.MessageCreateMarket
	(*MessageSubmitPrediction)(nil),     // 17: types.MessageSubmitPrediction
	(*MessageClaimWinnings)(nil),        // 18: types.MessageClaimWinnings
	(*MessageResolveMarket)(nil),        // 19: types.MessageResolveMarket
	(*MessageRegisterResolver)(nil),     // 20: types.MessageRegisterResolver
	(*MessageProposeOutcome)(nil),       // 21: types.MessageProposeOutcome
	(*MessageFileDispute)(nil),          // 22: types.MessageFileDispute
	(*MessageCommitVote)(nil),           // 23: types.MessageCommitVote
	(*MessageRevealVote)(nil),           // 24: types.MessageRevealVote
	(*MessageTallyVotes)(nil),           // 25: types.MessageTallyVotes
	(*MessageFinalizeMarket)(nil),       // 26: types.MessageFinalizeMarket
	(*MessageClaimSlash)(nil),           // 27: types.MessageClaimSlash
	(*MessageReclaimStake)(nil),         // 28: types.MessageReclaimStake
	(*MessageForfeitPosition)(nil),      // 29: types.MessageForfeitPosition
	(*MessageClaimBuilderReward)(nil),   // 30: types.MessageClaimBuilderReward
	(*MessageClaimCreatorFee)(nil),      // 31: types.MessageClaimCreatorFee
	(*MessageClaimResolverReward)(nil),  // 32: types.MessageClaimResolverReward
	(*LastClaimedBlock)(nil),            // 33: types.LastClaimedBlock
	(*MessageClaimCommunityReward)(nil), // 34: types.MessageClaimCommunityReward
	(*MessageClaimInvestorReward)(nil),  // 35: types.MessageClaimInvestorReward
	(*MessageClaimProtocolReward)(nil),  // 36: types.MessageClaimProtocolReward
	(*MessageCancelMarket)(nil),         // 37: types.MessageCancelMarket
	(*MessageUnstakeResolver)(nil),      // 38: types.MessageUnstakeResolver
	(*MessageClaimUnbondedStake)(nil),   // 39: types.MessageClaimUnbondedStake
	(*ResolverIndex)(nil),               // 40: types.ResolverIndex
	(*MarketIndex)(nil),                 // 41: types.MarketIndex
	(*GlobalStats)(nil),                 // 42: types.GlobalStats
	(*any1.Any)(nil),                    // 43: google.protobuf.Any
}
var file_tx_proto_depIdxs = []int32{
	43, // 0: types.Transaction.msg:type_name -> google.protobuf.Any
	0,  // 1: types.Transaction.signature:type_name -> types.Signature
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
