// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: account.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An account is a structure that holds funds and can send or receive transactions using a crypto key pair
// Each account has a unique address and a balance, think a bank account - but managed by the blockchain
// instead of a bank
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address: the short version of a public key
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// amount: the balance of funds the account has
	Amount        uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // NOTE: CAN EXTEND FUNCTIONALITY BY ADDING ADDITIONAL FIELDS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Account) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// A pool is like an account without an owner, holding funds that are managed directly by the blockchain protocol
// It's very similar to an account but instead of an address it has a unique ID and operates based on predefined
// blockchain rules rather than individual control
type Pool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id: the unique identifier of the pool
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// amount: the balance of funds the pool has
	Amount        uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *Pool) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pool) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Supply mirrors Canopy's lib.Supply (lib/.proto/account.proto). Plugins
// unmarshal the singleton stored at SupplyPrefix() to read network-wide
// totals: total minted, total staked (including delegations), per-committee
// stake aggregates, and per-committee delegate-only aggregates. Field
// numbers MUST match lib.Supply so proto wire-format decode succeeds.
type Supply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total: total tokens existing in the system (minted minus burned)
	Total uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// staked: total locked tokens (includes delegations)
	Staked uint64 `protobuf:"varint,2,opt,name=staked,proto3" json:"staked,omitempty"`
	// delegated_only: locked tokens that are delegate-only
	DelegatedOnly uint64 `protobuf:"varint,3,opt,name=delegated_only,json=delegatedOnly,proto3" json:"delegatedOnly"` // @gotags: json:"delegatedOnly"
	// committee_staked: per-committee staked totals (Pool.id = chainId,
	// Pool.amount = staked uCNPY), sorted by stake
	CommitteeStaked []*Pool `protobuf:"bytes,4,rep,name=committee_staked,json=committeeStaked,proto3" json:"committeeStaked"` // @gotags: json:"committeeStaked"
	// committee_delegated_only: per-committee delegate-only totals
	CommitteeDelegatedOnly []*Pool `protobuf:"bytes,5,rep,name=committee_delegated_only,json=committeeDelegatedOnly,proto3" json:"committeeDelegatedOnly"` // @gotags: json:"committeeDelegatedOnly"
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Supply) Reset() {
	*x = Supply{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Supply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Supply) ProtoMessage() {}

func (x *Supply) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Supply.ProtoReflect.Descriptor instead.
func (*Supply) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *Supply) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Supply) GetStaked() uint64 {
	if x != nil {
		return x.Staked
	}
	return 0
}

func (x *Supply) GetDelegatedOnly() uint64 {
	if x != nil {
		return x.DelegatedOnly
	}
	return 0
}

func (x *Supply) GetCommitteeStaked() []*Pool {
	if x != nil {
		return x.CommitteeStaked
	}
	return nil
}

func (x *Supply) GetCommitteeDelegatedOnly() []*Pool {
	if x != nil {
		return x.CommitteeDelegatedOnly
	}
	return nil
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\x05types\";\n" +
	"\aAccount\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\".\n" +
	"\x04Pool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"\xdc\x01\n" +
	"\x06Supply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x16\n" +
	"\x06staked\x18\x02 \x01(\x04R\x06staked\x12%\n" +
	"\x0edelegated_only\x18\x03 \x01(\x04R\rdelegatedOnly\x126\n" +
	"\x10committee_staked\x18\x04 \x03(\v2\v.types.PoolR\x0fcommitteeStaked\x12E\n" +
	"\x18committee_delegated_only\x18\x05 \x03(\v2\v.types.PoolR\x16committeeDelegatedOnlyB.Z,github.com/canopy-network/go-plugin/contractb\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_account_proto_goTypes = []any{
	(*Account)(nil), // 0: types.Account
	(*Pool)(nil),    // 1: types.Pool
	(*Supply)(nil),  // 2: types.Supply
}
var file_account_proto_depIdxs = []int32{
	1, // 0: types.Supply.committee_staked:type_name -> types.Pool
	1, // 1: types.Supply.committee_delegated_only:type_name -> types.Pool
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
