// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: arbor.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageCreateMarket creates a new isolated lending market (ARCM §3, §19.2)
type MessageCreateMarket struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MarketId             string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	CollateralAssetId    string                 `protobuf:"bytes,2,opt,name=collateral_asset_id,json=collateralAssetId,proto3" json:"collateral_asset_id,omitempty"`
	DebtAssetId          string                 `protobuf:"bytes,3,opt,name=debt_asset_id,json=debtAssetId,proto3" json:"debt_asset_id,omitempty"`
	AssetTier            uint32                 `protobuf:"varint,4,opt,name=asset_tier,json=assetTier,proto3" json:"asset_tier,omitempty"`                        // 0-4, ARCM §4 LTV table
	ReserveFactorBps     uint64                 `protobuf:"varint,5,opt,name=reserve_factor_bps,json=reserveFactorBps,proto3" json:"reserve_factor_bps,omitempty"` // 200-3000 bps, AYIS §13
	Creator              []byte                 `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	AuthorizedSubmitters [][]byte               `protobuf:"bytes,7,rep,name=authorized_submitters,json=authorizedSubmitters,proto3" json:"authorized_submitters,omitempty"` // ARCM §10 permissioned price feed;
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MessageCreateMarket) Reset() {
	*x = MessageCreateMarket{}
	mi := &file_arbor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreateMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreateMarket) ProtoMessage() {}

func (x *MessageCreateMarket) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreateMarket.ProtoReflect.Descriptor instead.
func (*MessageCreateMarket) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{0}
}

func (x *MessageCreateMarket) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageCreateMarket) GetCollateralAssetId() string {
	if x != nil {
		return x.CollateralAssetId
	}
	return ""
}

func (x *MessageCreateMarket) GetDebtAssetId() string {
	if x != nil {
		return x.DebtAssetId
	}
	return ""
}

func (x *MessageCreateMarket) GetAssetTier() uint32 {
	if x != nil {
		return x.AssetTier
	}
	return 0
}

func (x *MessageCreateMarket) GetReserveFactorBps() uint64 {
	if x != nil {
		return x.ReserveFactorBps
	}
	return 0
}

func (x *MessageCreateMarket) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *MessageCreateMarket) GetAuthorizedSubmitters() [][]byte {
	if x != nil {
		return x.AuthorizedSubmitters
	}
	return nil
}

// MessageUpdateMarketParams updates governance-bounded per-market params (ARCM §13, §15)
type MessageUpdateMarketParams struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MarketId         string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Authority        []byte                 `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	ReserveFactorBps uint64                 `protobuf:"varint,3,opt,name=reserve_factor_bps,json=reserveFactorBps,proto3" json:"reserve_factor_bps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageUpdateMarketParams) Reset() {
	*x = MessageUpdateMarketParams{}
	mi := &file_arbor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdateMarketParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdateMarketParams) ProtoMessage() {}

func (x *MessageUpdateMarketParams) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdateMarketParams.ProtoReflect.Descriptor instead.
func (*MessageUpdateMarketParams) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{1}
}

func (x *MessageUpdateMarketParams) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageUpdateMarketParams) GetAuthority() []byte {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *MessageUpdateMarketParams) GetReserveFactorBps() uint64 {
	if x != nil {
		return x.ReserveFactorBps
	}
	return 0
}

// MessagePauseMarket halts a market via governance/risk-committee action (ARCM §13, §16)
type MessagePauseMarket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Authority     []byte                 `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePauseMarket) Reset() {
	*x = MessagePauseMarket{}
	mi := &file_arbor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePauseMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePauseMarket) ProtoMessage() {}

func (x *MessagePauseMarket) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePauseMarket.ProtoReflect.Descriptor instead.
func (*MessagePauseMarket) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{2}
}

func (x *MessagePauseMarket) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessagePauseMarket) GetAuthority() []byte {
	if x != nil {
		return x.Authority
	}
	return nil
}

// MessageResumeMarket resumes a paused market
type MessageResumeMarket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Authority     []byte                 `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResumeMarket) Reset() {
	*x = MessageResumeMarket{}
	mi := &file_arbor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResumeMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResumeMarket) ProtoMessage() {}

func (x *MessageResumeMarket) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResumeMarket.ProtoReflect.Descriptor instead.
func (*MessageResumeMarket) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{3}
}

func (x *MessageResumeMarket) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageResumeMarket) GetAuthority() []byte {
	if x != nil {
		return x.Authority
	}
	return nil
}

// MessageDeprecateMarket permanently retires a market
type MessageDeprecateMarket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Authority     []byte                 `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeprecateMarket) Reset() {
	*x = MessageDeprecateMarket{}
	mi := &file_arbor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeprecateMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeprecateMarket) ProtoMessage() {}

func (x *MessageDeprecateMarket) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeprecateMarket.ProtoReflect.Descriptor instead.
func (*MessageDeprecateMarket) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{4}
}

func (x *MessageDeprecateMarket) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageDeprecateMarket) GetAuthority() []byte {
	if x != nil {
		return x.Authority
	}
	return nil
}

// MessageUpdatePrice submits a permissioned price feed reading
type MessageUpdatePrice struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AssetId string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"` // must match this market's collateral_asset_id
	// or debt_asset_id (checked at DeliverTx)
	Price         uint64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"` // USD per unit, x1e8
	ConfidenceBps uint32 `protobuf:"varint,3,opt,name=confidence_bps,json=confidenceBps,proto3" json:"confidence_bps,omitempty"`
	Submitter     []byte `protobuf:"bytes,4,opt,name=submitter,proto3" json:"submitter,omitempty"`
	MarketId      string `protobuf:"bytes,5,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"` // scopes this submission to one market's
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUpdatePrice) Reset() {
	*x = MessageUpdatePrice{}
	mi := &file_arbor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdatePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdatePrice) ProtoMessage() {}

func (x *MessageUpdatePrice) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdatePrice.ProtoReflect.Descriptor instead.
func (*MessageUpdatePrice) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{5}
}

func (x *MessageUpdatePrice) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *MessageUpdatePrice) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MessageUpdatePrice) GetConfidenceBps() uint32 {
	if x != nil {
		return x.ConfidenceBps
	}
	return 0
}

func (x *MessageUpdatePrice) GetSubmitter() []byte {
	if x != nil {
		return x.Submitter
	}
	return nil
}

func (x *MessageUpdatePrice) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

// MessageDepositCollateral posts collateral against a borrower position
type MessageDepositCollateral struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Quantity      uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"` // native units, 9-decimal convention (ARCM §2.1a)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDepositCollateral) Reset() {
	*x = MessageDepositCollateral{}
	mi := &file_arbor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDepositCollateral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDepositCollateral) ProtoMessage() {}

func (x *MessageDepositCollateral) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDepositCollateral.ProtoReflect.Descriptor instead.
func (*MessageDepositCollateral) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{6}
}

func (x *MessageDepositCollateral) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageDepositCollateral) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageDepositCollateral) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// MessageWithdrawCollateral removes collateral, subject to post-withdrawal HF check
type MessageWithdrawCollateral struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Quantity      uint64                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithdrawCollateral) Reset() {
	*x = MessageWithdrawCollateral{}
	mi := &file_arbor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithdrawCollateral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithdrawCollateral) ProtoMessage() {}

func (x *MessageWithdrawCollateral) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithdrawCollateral.ProtoReflect.Descriptor instead.
func (*MessageWithdrawCollateral) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{7}
}

func (x *MessageWithdrawCollateral) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageWithdrawCollateral) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageWithdrawCollateral) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// MessageDeposit supplies the market's asset in exchange for aToken shares (AYIS MintShares)
type MessageDeposit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // native asset units
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeposit) Reset() {
	*x = MessageDeposit{}
	mi := &file_arbor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeposit) ProtoMessage() {}

func (x *MessageDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeposit.ProtoReflect.Descriptor instead.
func (*MessageDeposit) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{8}
}

func (x *MessageDeposit) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageDeposit) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageDeposit) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// MessageWithdraw redeems aToken shares for the underlying asset (AYIS RedeemShares)
type MessageWithdraw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Shares        uint64                 `protobuf:"varint,3,opt,name=shares,proto3" json:"shares,omitempty"` // aToken shares, not underlying amount
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithdraw) Reset() {
	*x = MessageWithdraw{}
	mi := &file_arbor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithdraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithdraw) ProtoMessage() {}

func (x *MessageWithdraw) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithdraw.ProtoReflect.Descriptor instead.
func (*MessageWithdraw) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{9}
}

func (x *MessageWithdraw) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageWithdraw) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageWithdraw) GetShares() uint64 {
	if x != nil {
		return x.Shares
	}
	return 0
}

// MessageBorrow opens or increases a borrow position against posted collateral
type MessageBorrow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	BorrowAmount  uint64                 `protobuf:"varint,3,opt,name=borrow_amount,json=borrowAmount,proto3" json:"borrow_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBorrow) Reset() {
	*x = MessageBorrow{}
	mi := &file_arbor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBorrow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBorrow) ProtoMessage() {}

func (x *MessageBorrow) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBorrow.ProtoReflect.Descriptor instead.
func (*MessageBorrow) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{10}
}

func (x *MessageBorrow) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageBorrow) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageBorrow) GetBorrowAmount() uint64 {
	if x != nil {
		return x.BorrowAmount
	}
	return 0
}

// MessageRepay reduces or closes a borrow position
type MessageRepay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RepayAmount   uint64                 `protobuf:"varint,3,opt,name=repay_amount,json=repayAmount,proto3" json:"repay_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRepay) Reset() {
	*x = MessageRepay{}
	mi := &file_arbor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRepay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRepay) ProtoMessage() {}

func (x *MessageRepay) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRepay.ProtoReflect.Descriptor instead.
func (*MessageRepay) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{11}
}

func (x *MessageRepay) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageRepay) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *MessageRepay) GetRepayAmount() uint64 {
	if x != nil {
		return x.RepayAmount
	}
	return 0
}

// MessageLiquidatePosition liquidates an undercollateralized borrower position
type MessageLiquidatePosition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarketId        string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Liquidator      []byte                 `protobuf:"bytes,2,opt,name=liquidator,proto3" json:"liquidator,omitempty"`
	BorrowerAddress []byte                 `protobuf:"bytes,3,opt,name=borrower_address,json=borrowerAddress,proto3" json:"borrower_address,omitempty"`
	RepayAmount     uint64                 `protobuf:"varint,4,opt,name=repay_amount,json=repayAmount,proto3" json:"repay_amount,omitempty"` // capped at debt x close_factor, ARCM §7
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageLiquidatePosition) Reset() {
	*x = MessageLiquidatePosition{}
	mi := &file_arbor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageLiquidatePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageLiquidatePosition) ProtoMessage() {}

func (x *MessageLiquidatePosition) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageLiquidatePosition.ProtoReflect.Descriptor instead.
func (*MessageLiquidatePosition) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{12}
}

func (x *MessageLiquidatePosition) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *MessageLiquidatePosition) GetLiquidator() []byte {
	if x != nil {
		return x.Liquidator
	}
	return nil
}

func (x *MessageLiquidatePosition) GetBorrowerAddress() []byte {
	if x != nil {
		return x.BorrowerAddress
	}
	return nil
}

func (x *MessageLiquidatePosition) GetRepayAmount() uint64 {
	if x != nil {
		return x.RepayAmount
	}
	return 0
}

// MessageSetAssetTier registers or updates an asset's canonical risk tier
// (0=Tier0/CNPY .. 3=Tier3/Restricted; Tier 4/Blacklisted is never stored,
// see state_keys.go PrefixAssetTier). Authority-gated -- single hardcoded
// address for now, standing in for the risk-committee multisig ARCM §13
// names as the intended actor for tier promotion/demotion; same disclosed-
// placeholder pattern as authorized_submitters above. Real governance-gated
// multisig/timelock is a future milestone, not implemented here.
type MessageSetAssetTier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Tier          uint32                 `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"` // 0-3 only; checked at DeliverTx
	Authority     []byte                 `protobuf:"bytes,3,opt,name=authority,proto3" json:"authority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSetAssetTier) Reset() {
	*x = MessageSetAssetTier{}
	mi := &file_arbor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSetAssetTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSetAssetTier) ProtoMessage() {}

func (x *MessageSetAssetTier) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSetAssetTier.ProtoReflect.Descriptor instead.
func (*MessageSetAssetTier) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{13}
}

func (x *MessageSetAssetTier) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *MessageSetAssetTier) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *MessageSetAssetTier) GetAuthority() []byte {
	if x != nil {
		return x.Authority
	}
	return nil
}

// MessageSetTreasuryCut sets the GLOBAL treasury_cut_bps governance parameter
// (see bad_debt_layer3.go's own doc comment on PrefixTreasuryArbor/
// PrefixTreasuryNASM being global, not per-market -- this parameter mirrors
// that scope). Unlike reserve_factor_bps (per-market, set via create_market/
// update_market_params), treasury_cut_bps applies uniformly to every
// market's interest accrual (AYIS Section 7 Step 10, extended): a single
// governance-set rate feeds Arbor's own protocol treasury ({40}) from every
// market's interest_earned, rather than each market creator choosing (and
// potentially free-riding by setting to 0) their own contribution to a
// shared, protocol-wide backstop. Bounds: 25-150 bps (0.25%-1.5%),
// deliberately narrower than reserve_factor_bps's 200-3000 -- Layer 3 (this
// treasury) is a secondary, lower-probability-of-use backstop behind Layer
// 2's per-market reserve, not a primary defense, so it should not tax lender
// yield as heavily. Floor raised from an initially-considered 10 bps: Layer
// 3 only fires after a market's OWN R_fund is already exhausted by a single
// shortfall, implying a real bad-debt event large enough to matter; too low
// a floor risks the treasury accumulating too slowly to ever meaningfully
// help, the same "looks wired but silently doesn't matter" failure mode
// this codebase's own discipline elsewhere exists to avoid. No market_id
// field -- this is a single global value, analogous to
// KeyForTreasuryArbor/KeyForTreasuryNASM's own no-argument, global-balance
// shape (state_keys.go).
type MessageSetTreasuryCut struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Authority      []byte                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	TreasuryCutBps uint64                 `protobuf:"varint,2,opt,name=treasury_cut_bps,json=treasuryCutBps,proto3" json:"treasury_cut_bps,omitempty"` // 25-150 bps, checked at DeliverTx
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageSetTreasuryCut) Reset() {
	*x = MessageSetTreasuryCut{}
	mi := &file_arbor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSetTreasuryCut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSetTreasuryCut) ProtoMessage() {}

func (x *MessageSetTreasuryCut) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSetTreasuryCut.ProtoReflect.Descriptor instead.
func (*MessageSetTreasuryCut) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{14}
}

func (x *MessageSetTreasuryCut) GetAuthority() []byte {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *MessageSetTreasuryCut) GetTreasuryCutBps() uint64 {
	if x != nil {
		return x.TreasuryCutBps
	}
	return 0
}

// MessageMintNusd opens a new NASM vault: locks eligible collateral
// (NASM Spec Section 3.1's N-0/N-1 tiers only, resolved via
// nasm_tier.go's ResolveNasmTier against ARCM's existing {29} registry --
// see that file's doc comment for why NASM does not maintain a separate
// registry) and mints newly-issued NUSD against it in one atomic
// transaction (NASM Spec Section 4.1).
//
// vault_id is caller-supplied, NOT derived (matches market_id's own
// precedent -- see ValidateVaultID/KeyForNasmVault in state_keys.go).
// This is a deliberate departure from BorrowerPosition's owner-address-
// keyed pattern: NASM Spec Section 5.2 requires vault ownership to be a
// transferable claim, which an address-derived key would foreclose. The
// caller chooses vault_id and it never changes for that vault's lifetime,
// even if ownership later transfers.
//
// KNOWN GAP, DISCLOSED: the per-tier mint concentration cap (NASM Spec
// Section 3.3, Max_tier_share_bps) is NOT enforced by this message as of
// this version. That check requires a running total-backing-value
// accumulator per tier, which does not exist in state yet (a range-scan
// over all {30} vaults at every mint was considered and rejected --
// unbounded per-transaction cost, the same anti-pattern
// KeyForPriceRecord's own market_id field was added to avoid; see
// update_price.go's doc comment). The accumulator will be added once
// burn_nusd exists, so it can be correctly kept in sync on both mint and
// burn from the start rather than shipping an increment-only value that
// silently drifts. Matches this codebase's established disclosure
// convention for known-deferred checks (see deposit.go's MIN_DEPOSIT
// comment, create_market.go's hardcoded MinReporters comment).
type MessageMintNusd struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	VaultId             string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Owner               []byte                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	CollateralAssetId   string                 `protobuf:"bytes,3,opt,name=collateral_asset_id,json=collateralAssetId,proto3" json:"collateral_asset_id,omitempty"`
	CollateralQuantity  uint64                 `protobuf:"varint,4,opt,name=collateral_quantity,json=collateralQuantity,proto3" json:"collateral_quantity,omitempty"`
	NusdAmountRequested uint64                 `protobuf:"varint,5,opt,name=nusd_amount_requested,json=nusdAmountRequested,proto3" json:"nusd_amount_requested,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MessageMintNusd) Reset() {
	*x = MessageMintNusd{}
	mi := &file_arbor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageMintNusd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMintNusd) ProtoMessage() {}

func (x *MessageMintNusd) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMintNusd.ProtoReflect.Descriptor instead.
func (*MessageMintNusd) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{15}
}

func (x *MessageMintNusd) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *MessageMintNusd) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *MessageMintNusd) GetCollateralAssetId() string {
	if x != nil {
		return x.CollateralAssetId
	}
	return ""
}

func (x *MessageMintNusd) GetCollateralQuantity() uint64 {
	if x != nil {
		return x.CollateralQuantity
	}
	return 0
}

func (x *MessageMintNusd) GetNusdAmountRequested() uint64 {
	if x != nil {
		return x.NusdAmountRequested
	}
	return 0
}

// MessageBurnNusd is the sole mechanism by which NUSD is removed from
// circulation and collateral released (NASM Consolidated Spec Section
// 4.2) -- owner-scoped only, no aggregate-pool redemption, no third-party
// vault seizure. sender MUST be the vault's current owner (checked at
// DeliverTx via NasmVault.Owner) -- there is no code path by which NUSD
// burned by holder A can release collateral from a vault owned by holder
// B (Section 4.2's own closing guarantee, Invariant N-I8).
//
// nusd_amount may exceed the vault's actual current debt (ScaledNusdDebt)
// -- DeliverTx computes compare-before-subtract (Section 4.2 Step 6) and
// only actually burns/debits up to current_debt, never more, regardless
// of what nusd_amount requests. This is NOT the same refund risk ARCM's
// repay.go's ErrRepayExceedsDebt was fixed to avoid (that fix closed a
// path where an escrow-less refund would have minted unbacked value);
// here, burn_nusd only ever debits NusdBalance for the true amount owed,
// never more than the sender already holds and never creating any new
// value -- structurally safer than a refund-by-minting design.
type MessageBurnNusd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Sender        []byte                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	NusdAmount    uint64                 `protobuf:"varint,3,opt,name=nusd_amount,json=nusdAmount,proto3" json:"nusd_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBurnNusd) Reset() {
	*x = MessageBurnNusd{}
	mi := &file_arbor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBurnNusd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBurnNusd) ProtoMessage() {}

func (x *MessageBurnNusd) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBurnNusd.ProtoReflect.Descriptor instead.
func (*MessageBurnNusd) Descriptor() ([]byte, []int) {
	return file_arbor_proto_rawDescGZIP(), []int{16}
}

func (x *MessageBurnNusd) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *MessageBurnNusd) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *MessageBurnNusd) GetNusdAmount() uint64 {
	if x != nil {
		return x.NusdAmount
	}
	return 0
}

var File_arbor_proto protoreflect.FileDescriptor

const file_arbor_proto_rawDesc = "" +
	"\n" +
	"\varbor.proto\x12\x05types\"\xa2\x02\n" +
	"\x13MessageCreateMarket\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12.\n" +
	"\x13collateral_asset_id\x18\x02 \x01(\tR\x11collateralAssetId\x12\"\n" +
	"\rdebt_asset_id\x18\x03 \x01(\tR\vdebtAssetId\x12\x1d\n" +
	"\n" +
	"asset_tier\x18\x04 \x01(\rR\tassetTier\x12,\n" +
	"\x12reserve_factor_bps\x18\x05 \x01(\x04R\x10reserveFactorBps\x12\x18\n" +
	"\acreator\x18\x06 \x01(\fR\acreator\x123\n" +
	"\x15authorized_submitters\x18\a \x03(\fR\x14authorizedSubmitters\"\x84\x01\n" +
	"\x19MessageUpdateMarketParams\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1c\n" +
	"\tauthority\x18\x02 \x01(\fR\tauthority\x12,\n" +
	"\x12reserve_factor_bps\x18\x03 \x01(\x04R\x10reserveFactorBps\"O\n" +
	"\x12MessagePauseMarket\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1c\n" +
	"\tauthority\x18\x02 \x01(\fR\tauthority\"P\n" +
	"\x13MessageResumeMarket\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1c\n" +
	"\tauthority\x18\x02 \x01(\fR\tauthority\"S\n" +
	"\x16MessageDeprecateMarket\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1c\n" +
	"\tauthority\x18\x02 \x01(\fR\tauthority\"\xa7\x01\n" +
	"\x12MessageUpdatePrice\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x04R\x05price\x12%\n" +
	"\x0econfidence_bps\x18\x03 \x01(\rR\rconfidenceBps\x12\x1c\n" +
	"\tsubmitter\x18\x04 \x01(\fR\tsubmitter\x12\x1b\n" +
	"\tmarket_id\x18\x05 \x01(\tR\bmarketId\"m\n" +
	"\x18MessageDepositCollateral\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\"n\n" +
	"\x19MessageWithdrawCollateral\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x04R\bquantity\"_\n" +
	"\x0eMessageDeposit\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"`\n" +
	"\x0fMessageWithdraw\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x16\n" +
	"\x06shares\x18\x03 \x01(\x04R\x06shares\"k\n" +
	"\rMessageBorrow\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12#\n" +
	"\rborrow_amount\x18\x03 \x01(\x04R\fborrowAmount\"h\n" +
	"\fMessageRepay\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12!\n" +
	"\frepay_amount\x18\x03 \x01(\x04R\vrepayAmount\"\xa5\x01\n" +
	"\x18MessageLiquidatePosition\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x1e\n" +
	"\n" +
	"liquidator\x18\x02 \x01(\fR\n" +
	"liquidator\x12)\n" +
	"\x10borrower_address\x18\x03 \x01(\fR\x0fborrowerAddress\x12!\n" +
	"\frepay_amount\x18\x04 \x01(\x04R\vrepayAmount\"b\n" +
	"\x13MessageSetAssetTier\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\rR\x04tier\x12\x1c\n" +
	"\tauthority\x18\x03 \x01(\fR\tauthority\"_\n" +
	"\x15MessageSetTreasuryCut\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\fR\tauthority\x12(\n" +
	"\x10treasury_cut_bps\x18\x02 \x01(\x04R\x0etreasuryCutBps\"\xd7\x01\n" +
	"\x0fMessageMintNusd\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\fR\x05owner\x12.\n" +
	"\x13collateral_asset_id\x18\x03 \x01(\tR\x11collateralAssetId\x12/\n" +
	"\x13collateral_quantity\x18\x04 \x01(\x04R\x12collateralQuantity\x122\n" +
	"\x15nusd_amount_requested\x18\x05 \x01(\x04R\x13nusdAmountRequested\"e\n" +
	"\x0fMessageBurnNusd\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\fR\x06sender\x12\x1f\n" +
	"\vnusd_amount\x18\x03 \x01(\x04R\n" +
	"nusdAmountB-Z+github.com/ARBOR-L/ARBOR/plugin/go/contractb\x06proto3"

var (
	file_arbor_proto_rawDescOnce sync.Once
	file_arbor_proto_rawDescData []byte
)

func file_arbor_proto_rawDescGZIP() []byte {
	file_arbor_proto_rawDescOnce.Do(func() {
		file_arbor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arbor_proto_rawDesc), len(file_arbor_proto_rawDesc)))
	})
	return file_arbor_proto_rawDescData
}

var file_arbor_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_arbor_proto_goTypes = []any{
	(*MessageCreateMarket)(nil),       // 0: types.MessageCreateMarket
	(*MessageUpdateMarketParams)(nil), // 1: types.MessageUpdateMarketParams
	(*MessagePauseMarket)(nil),        // 2: types.MessagePauseMarket
	(*MessageResumeMarket)(nil),       // 3: types.MessageResumeMarket
	(*MessageDeprecateMarket)(nil),    // 4: types.MessageDeprecateMarket
	(*MessageUpdatePrice)(nil),        // 5: types.MessageUpdatePrice
	(*MessageDepositCollateral)(nil),  // 6: types.MessageDepositCollateral
	(*MessageWithdrawCollateral)(nil), // 7: types.MessageWithdrawCollateral
	(*MessageDeposit)(nil),            // 8: types.MessageDeposit
	(*MessageWithdraw)(nil),           // 9: types.MessageWithdraw
	(*MessageBorrow)(nil),             // 10: types.MessageBorrow
	(*MessageRepay)(nil),              // 11: types.MessageRepay
	(*MessageLiquidatePosition)(nil),  // 12: types.MessageLiquidatePosition
	(*MessageSetAssetTier)(nil),       // 13: types.MessageSetAssetTier
	(*MessageSetTreasuryCut)(nil),     // 14: types.MessageSetTreasuryCut
	(*MessageMintNusd)(nil),           // 15: types.MessageMintNusd
	(*MessageBurnNusd)(nil),           // 16: types.MessageBurnNusd
}
var file_arbor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arbor_proto_init() }
func file_arbor_proto_init() {
	if File_arbor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arbor_proto_rawDesc), len(file_arbor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arbor_proto_goTypes,
		DependencyIndexes: file_arbor_proto_depIdxs,
		MessageInfos:      file_arbor_proto_msgTypes,
	}.Build()
	File_arbor_proto = out.File
	file_arbor_proto_goTypes = nil
	file_arbor_proto_depIdxs = nil
}
