// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: arbor_state.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MarketStatus mirrors ARCM's market.status enum (Section 9, Section 13, Section 16).
type MarketStatus int32

const (
	MarketStatus_ACTIVE     MarketStatus = 0
	MarketStatus_PAUSED     MarketStatus = 1 // governance action (ARCM Section 13)
	MarketStatus_INSOLVENT  MarketStatus = 2 // loss_factor reached zero (AYIS Section 5.4.3, I11)
	MarketStatus_DEPRECATED MarketStatus = 3 // permanently retired (ARCM Section 19.2)
)

// Enum value maps for MarketStatus.
var (
	MarketStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "PAUSED",
		2: "INSOLVENT",
		3: "DEPRECATED",
	}
	MarketStatus_value = map[string]int32{
		"ACTIVE":     0,
		"PAUSED":     1,
		"INSOLVENT":  2,
		"DEPRECATED": 3,
	}
)

func (x MarketStatus) Enum() *MarketStatus {
	p := new(MarketStatus)
	*p = x
	return p
}

func (x MarketStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_arbor_state_proto_enumTypes[0].Descriptor()
}

func (MarketStatus) Type() protoreflect.EnumType {
	return &file_arbor_state_proto_enumTypes[0]
}

func (x MarketStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketStatus.Descriptor instead.
func (MarketStatus) EnumDescriptor() ([]byte, []int) {
	return file_arbor_state_proto_rawDescGZIP(), []int{0}
}

// Market is the {16} record: core market metadata plus the flags and counters
// ARCM's bad-debt waterfall and freeze mechanism operate on. See ARCM v3.11.1
// Section 19.1 for the canonical field set this implements.
type Market struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	MarketId                  string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	CollateralAssetId         string                 `protobuf:"bytes,2,opt,name=collateral_asset_id,json=collateralAssetId,proto3" json:"collateral_asset_id,omitempty"`
	DebtAssetId               string                 `protobuf:"bytes,3,opt,name=debt_asset_id,json=debtAssetId,proto3" json:"debt_asset_id,omitempty"`
	AssetTier                 uint32                 `protobuf:"varint,4,opt,name=asset_tier,json=assetTier,proto3" json:"asset_tier,omitempty"`                        // 0-4, ARCM Section 4 LTV table
	ReserveFactorBps          uint64                 `protobuf:"varint,5,opt,name=reserve_factor_bps,json=reserveFactorBps,proto3" json:"reserve_factor_bps,omitempty"` // AYIS Section 13
	Creator                   []byte                 `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Status                    MarketStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=types.MarketStatus" json:"status,omitempty"`
	IndexOverflowHalted       bool                   `protobuf:"varint,8,opt,name=index_overflow_halted,json=indexOverflowHalted,proto3" json:"index_overflow_halted,omitempty"`                       // ARCM Section 9.3a
	Layer4PendingCount        uint32                 `protobuf:"varint,9,opt,name=layer4_pending_count,json=layer4PendingCount,proto3" json:"layer4_pending_count,omitempty"`                          // ARCM Section 9.2b
	Layer4PendingBadDebtTotal []byte                 `protobuf:"bytes,10,opt,name=layer4_pending_bad_debt_total,json=layer4PendingBadDebtTotal,proto3" json:"layer4_pending_bad_debt_total,omitempty"` // uint128, EncodeUint128 raw bytes (widened v3.11, L2-widen)
	TotalBorrowed             uint64                 `protobuf:"varint,11,opt,name=total_borrowed,json=totalBorrowed,proto3" json:"total_borrowed,omitempty"`                                          // guarded via applyDebtDelta, C1
	TotalSupplied             uint64                 `protobuf:"varint,12,opt,name=total_supplied,json=totalSupplied,proto3" json:"total_supplied,omitempty"`                                          // ARCM Section 19.2.1b
	LastAccrualBlock          uint64                 `protobuf:"varint,13,opt,name=last_accrual_block,json=lastAccrualBlock,proto3" json:"last_accrual_block,omitempty"`                               // AYIS Section 7 Step 11
	AuthorizedSubmitters      [][]byte               `protobuf:"bytes,14,rep,name=authorized_submitters,json=authorizedSubmitters,proto3" json:"authorized_submitters,omitempty"`                      // ARCM Section 10 permissioned
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_arbor_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_arbor_state_proto_rawDescGZIP(), []int{0}
}

func (x *Market) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Market) GetCollateralAssetId() string {
	if x != nil {
		return x.CollateralAssetId
	}
	return ""
}

func (x *Market) GetDebtAssetId() string {
	if x != nil {
		return x.DebtAssetId
	}
	return ""
}

func (x *Market) GetAssetTier() uint32 {
	if x != nil {
		return x.AssetTier
	}
	return 0
}

func (x *Market) GetReserveFactorBps() uint64 {
	if x != nil {
		return x.ReserveFactorBps
	}
	return 0
}

func (x *Market) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *Market) GetStatus() MarketStatus {
	if x != nil {
		return x.Status
	}
	return MarketStatus_ACTIVE
}

func (x *Market) GetIndexOverflowHalted() bool {
	if x != nil {
		return x.IndexOverflowHalted
	}
	return false
}

func (x *Market) GetLayer4PendingCount() uint32 {
	if x != nil {
		return x.Layer4PendingCount
	}
	return 0
}

func (x *Market) GetLayer4PendingBadDebtTotal() []byte {
	if x != nil {
		return x.Layer4PendingBadDebtTotal
	}
	return nil
}

func (x *Market) GetTotalBorrowed() uint64 {
	if x != nil {
		return x.TotalBorrowed
	}
	return 0
}

func (x *Market) GetTotalSupplied() uint64 {
	if x != nil {
		return x.TotalSupplied
	}
	return 0
}

func (x *Market) GetLastAccrualBlock() uint64 {
	if x != nil {
		return x.LastAccrualBlock
	}
	return 0
}

func (x *Market) GetAuthorizedSubmitters() [][]byte {
	if x != nil {
		return x.AuthorizedSubmitters
	}
	return nil
}

// BorrowerPosition is the {17} record (ARCM Section 6, AYIS Section 6).
type BorrowerPosition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MarketId           string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Address            []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	CollateralQuantity uint64                 `protobuf:"varint,3,opt,name=collateral_quantity,json=collateralQuantity,proto3" json:"collateral_quantity,omitempty"`
	DebtPrincipal      uint64                 `protobuf:"varint,4,opt,name=debt_principal,json=debtPrincipal,proto3" json:"debt_principal,omitempty"`
	BorrowIndexAtOpen  []byte                 `protobuf:"bytes,5,opt,name=borrow_index_at_open,json=borrowIndexAtOpen,proto3" json:"borrow_index_at_open,omitempty"` // uint128, EncodeUint128 raw bytes -- B_index snapshot at open
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BorrowerPosition) Reset() {
	*x = BorrowerPosition{}
	mi := &file_arbor_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowerPosition) ProtoMessage() {}

func (x *BorrowerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowerPosition.ProtoReflect.Descriptor instead.
func (*BorrowerPosition) Descriptor() ([]byte, []int) {
	return file_arbor_state_proto_rawDescGZIP(), []int{1}
}

func (x *BorrowerPosition) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *BorrowerPosition) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *BorrowerPosition) GetCollateralQuantity() uint64 {
	if x != nil {
		return x.CollateralQuantity
	}
	return 0
}

func (x *BorrowerPosition) GetDebtPrincipal() uint64 {
	if x != nil {
		return x.DebtPrincipal
	}
	return 0
}

func (x *BorrowerPosition) GetBorrowIndexAtOpen() []byte {
	if x != nil {
		return x.BorrowIndexAtOpen
	}
	return nil
}

// PriceRecord is one {19} entry, keyed by (asset_id, submitter) --
// ARCM Section 10's permissioned price feed. Multiple independent
// submitters each write their own record per asset; quorum (MIN_REPORTERS)
// and deviation (30% circuit breaker) are resolved by aggregating across
// all of an asset's records at READ time, not by any single record being
// authoritative on its own. block_height is chain-assigned at write time
// (not submitter-supplied) for Section 11's staleness checks.
type PriceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Submitter     []byte                 `protobuf:"bytes,2,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Price         uint64                 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"` // USD per unit, x1e8
	ConfidenceBps uint32                 `protobuf:"varint,4,opt,name=confidence_bps,json=confidenceBps,proto3" json:"confidence_bps,omitempty"`
	BlockHeight   uint64                 `protobuf:"varint,5,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRecord) Reset() {
	*x = PriceRecord{}
	mi := &file_arbor_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRecord) ProtoMessage() {}

func (x *PriceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRecord.ProtoReflect.Descriptor instead.
func (*PriceRecord) Descriptor() ([]byte, []int) {
	return file_arbor_state_proto_rawDescGZIP(), []int{2}
}

func (x *PriceRecord) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *PriceRecord) GetSubmitter() []byte {
	if x != nil {
		return x.Submitter
	}
	return nil
}

func (x *PriceRecord) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceRecord) GetConfidenceBps() uint32 {
	if x != nil {
		return x.ConfidenceBps
	}
	return 0
}

func (x *PriceRecord) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// LenderPosition is the {24} record (AYIS Section 5.1).
type LenderPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Shares        uint64                 `protobuf:"varint,3,opt,name=shares,proto3" json:"shares,omitempty"`
	DepositBlock  uint64                 `protobuf:"varint,4,opt,name=deposit_block,json=depositBlock,proto3" json:"deposit_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LenderPosition) Reset() {
	*x = LenderPosition{}
	mi := &file_arbor_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LenderPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LenderPosition) ProtoMessage() {}

func (x *LenderPosition) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LenderPosition.ProtoReflect.Descriptor instead.
func (*LenderPosition) Descriptor() ([]byte, []int) {
	return file_arbor_state_proto_rawDescGZIP(), []int{3}
}

func (x *LenderPosition) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *LenderPosition) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *LenderPosition) GetShares() uint64 {
	if x != nil {
		return x.Shares
	}
	return 0
}

func (x *LenderPosition) GetDepositBlock() uint64 {
	if x != nil {
		return x.DepositBlock
	}
	return 0
}

// LossFactorQueueEntry is a {28} record (AYIS Section 12.4, ARCM v3.11.1
// Section 9.3b Rule 3). One entry per market_id: a backstop-triggered
// Layer 4 exhaustion enqueues a bad_debt amount here (via
// EnqueueLossFactorApplication) rather than calling ApplyLossFactor()
// synchronously, so BeginBlock's ProcessLossFactorQueue() can drain it
// later in the same call under Section 12.3's Accrual Ordering Contract
// (AccrueInterest MUST run before this queue drains). A market has at
// most one outstanding entry at a time -- K3's idempotency guard in
// ApplyLossFactor() means a second enqueue against an already-Insolvent
// market is a no-op at drain time, not a second queued entry, so this
// message does not need its own sequence/ordering field.
type LossFactorQueueEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	BadDebt       uint64                 `protobuf:"varint,2,opt,name=bad_debt,json=badDebt,proto3" json:"bad_debt,omitempty"`
	EnqueuedBlock uint64                 `protobuf:"varint,3,opt,name=enqueued_block,json=enqueuedBlock,proto3" json:"enqueued_block,omitempty"` // observability only; not read by any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LossFactorQueueEntry) Reset() {
	*x = LossFactorQueueEntry{}
	mi := &file_arbor_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LossFactorQueueEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LossFactorQueueEntry) ProtoMessage() {}

func (x *LossFactorQueueEntry) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LossFactorQueueEntry.ProtoReflect.Descriptor instead.
func (*LossFactorQueueEntry) Descriptor() ([]byte, []int) {
	return file_arbor_state_proto_rawDescGZIP(), []int{4}
}

func (x *LossFactorQueueEntry) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *LossFactorQueueEntry) GetBadDebt() uint64 {
	if x != nil {
		return x.BadDebt
	}
	return 0
}

func (x *LossFactorQueueEntry) GetEnqueuedBlock() uint64 {
	if x != nil {
		return x.EnqueuedBlock
	}
	return 0
}

var File_arbor_state_proto protoreflect.FileDescriptor

const file_arbor_state_proto_rawDesc = "" +
	"\n" +
	"\x11arbor_state.proto\x12\x05types\"\xe6\x04\n" +
	"\x06Market\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12.\n" +
	"\x13collateral_asset_id\x18\x02 \x01(\tR\x11collateralAssetId\x12\"\n" +
	"\rdebt_asset_id\x18\x03 \x01(\tR\vdebtAssetId\x12\x1d\n" +
	"\n" +
	"asset_tier\x18\x04 \x01(\rR\tassetTier\x12,\n" +
	"\x12reserve_factor_bps\x18\x05 \x01(\x04R\x10reserveFactorBps\x12\x18\n" +
	"\acreator\x18\x06 \x01(\fR\acreator\x12+\n" +
	"\x06status\x18\a \x01(\x0e2\x13.types.MarketStatusR\x06status\x122\n" +
	"\x15index_overflow_halted\x18\b \x01(\bR\x13indexOverflowHalted\x120\n" +
	"\x14layer4_pending_count\x18\t \x01(\rR\x12layer4PendingCount\x12@\n" +
	"\x1dlayer4_pending_bad_debt_total\x18\n" +
	" \x01(\fR\x19layer4PendingBadDebtTotal\x12%\n" +
	"\x0etotal_borrowed\x18\v \x01(\x04R\rtotalBorrowed\x12%\n" +
	"\x0etotal_supplied\x18\f \x01(\x04R\rtotalSupplied\x12,\n" +
	"\x12last_accrual_block\x18\r \x01(\x04R\x10lastAccrualBlock\x123\n" +
	"\x15authorized_submitters\x18\x0e \x03(\fR\x14authorizedSubmitters\"\xd2\x01\n" +
	"\x10BorrowerPosition\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12/\n" +
	"\x13collateral_quantity\x18\x03 \x01(\x04R\x12collateralQuantity\x12%\n" +
	"\x0edebt_principal\x18\x04 \x01(\x04R\rdebtPrincipal\x12/\n" +
	"\x14borrow_index_at_open\x18\x05 \x01(\fR\x11borrowIndexAtOpen\"\xa6\x01\n" +
	"\vPriceRecord\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x1c\n" +
	"\tsubmitter\x18\x02 \x01(\fR\tsubmitter\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x04R\x05price\x12%\n" +
	"\x0econfidence_bps\x18\x04 \x01(\rR\rconfidenceBps\x12!\n" +
	"\fblock_height\x18\x05 \x01(\x04R\vblockHeight\"\x84\x01\n" +
	"\x0eLenderPosition\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x16\n" +
	"\x06shares\x18\x03 \x01(\x04R\x06shares\x12#\n" +
	"\rdeposit_block\x18\x04 \x01(\x04R\fdepositBlock\"u\n" +
	"\x14LossFactorQueueEntry\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\bbad_debt\x18\x02 \x01(\x04R\abadDebt\x12%\n" +
	"\x0eenqueued_block\x18\x03 \x01(\x04R\renqueuedBlock*E\n" +
	"\fMarketStatus\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x00\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x01\x12\r\n" +
	"\tINSOLVENT\x10\x02\x12\x0e\n" +
	"\n" +
	"DEPRECATED\x10\x03B-Z+github.com/ARBOR-L/ARBOR/plugin/go/contractb\x06proto3"

var (
	file_arbor_state_proto_rawDescOnce sync.Once
	file_arbor_state_proto_rawDescData []byte
)

func file_arbor_state_proto_rawDescGZIP() []byte {
	file_arbor_state_proto_rawDescOnce.Do(func() {
		file_arbor_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arbor_state_proto_rawDesc), len(file_arbor_state_proto_rawDesc)))
	})
	return file_arbor_state_proto_rawDescData
}

var file_arbor_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_arbor_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_arbor_state_proto_goTypes = []any{
	(MarketStatus)(0),            // 0: types.MarketStatus
	(*Market)(nil),               // 1: types.Market
	(*BorrowerPosition)(nil),     // 2: types.BorrowerPosition
	(*PriceRecord)(nil),          // 3: types.PriceRecord
	(*LenderPosition)(nil),       // 4: types.LenderPosition
	(*LossFactorQueueEntry)(nil), // 5: types.LossFactorQueueEntry
}
var file_arbor_state_proto_depIdxs = []int32{
	0, // 0: types.Market.status:type_name -> types.MarketStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_arbor_state_proto_init() }
func file_arbor_state_proto_init() {
	if File_arbor_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arbor_state_proto_rawDesc), len(file_arbor_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arbor_state_proto_goTypes,
		DependencyIndexes: file_arbor_state_proto_depIdxs,
		EnumInfos:         file_arbor_state_proto_enumTypes,
		MessageInfos:      file_arbor_state_proto_msgTypes,
	}.Build()
	File_arbor_state_proto = out.File
	file_arbor_state_proto_goTypes = nil
	file_arbor_state_proto_depIdxs = nil
}
