// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: arbor_events.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventIndexEncodingOverflowHalted fires when a BeginBlock-context TryEncodeUint128
// call fails for B_index, S_rate, or R_fund's interest-routing leg. Sets
// index_overflow_halted for this market only.
type EventIndexEncodingOverflowHalted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MarketId       string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Field          string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`                                         // "B_index" | "S_rate" | "R_fund"
	AttemptedValue string                 `protobuf:"bytes,3,opt,name=attempted_value,json=attemptedValue,proto3" json:"attempted_value,omitempty"` // decimal string, the value that failed to encode
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventIndexEncodingOverflowHalted) Reset() {
	*x = EventIndexEncodingOverflowHalted{}
	mi := &file_arbor_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventIndexEncodingOverflowHalted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventIndexEncodingOverflowHalted) ProtoMessage() {}

func (x *EventIndexEncodingOverflowHalted) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventIndexEncodingOverflowHalted.ProtoReflect.Descriptor instead.
func (*EventIndexEncodingOverflowHalted) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventIndexEncodingOverflowHalted) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventIndexEncodingOverflowHalted) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *EventIndexEncodingOverflowHalted) GetAttemptedValue() string {
	if x != nil {
		return x.AttemptedValue
	}
	return ""
}

// EventInsolventMarketValueRecovered fires each time recovered value routes to
// R_fund for an Insolvent market (interest, repay principal, or liquidation proceeds).
type EventInsolventMarketValueRecovered struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarketId        string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	RecoveredAmount uint64                 `protobuf:"varint,2,opt,name=recovered_amount,json=recoveredAmount,proto3" json:"recovered_amount,omitempty"`
	Source          string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // "interest" | "repay_principal" | "liquidation_proceeds"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventInsolventMarketValueRecovered) Reset() {
	*x = EventInsolventMarketValueRecovered{}
	mi := &file_arbor_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventInsolventMarketValueRecovered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInsolventMarketValueRecovered) ProtoMessage() {}

func (x *EventInsolventMarketValueRecovered) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInsolventMarketValueRecovered.ProtoReflect.Descriptor instead.
func (*EventInsolventMarketValueRecovered) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventInsolventMarketValueRecovered) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventInsolventMarketValueRecovered) GetRecoveredAmount() uint64 {
	if x != nil {
		return x.RecoveredAmount
	}
	return 0
}

func (x *EventInsolventMarketValueRecovered) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// EventTotalSuppliedDustClamp fires when a withdrawal clamps market.total_supplied to zero
type EventTotalSuppliedDustClamp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarketId        string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	ActualWithdrawn uint64                 `protobuf:"varint,2,opt,name=actual_withdrawn,json=actualWithdrawn,proto3" json:"actual_withdrawn,omitempty"`
	PreClampValue   uint64                 `protobuf:"varint,3,opt,name=pre_clamp_value,json=preClampValue,proto3" json:"pre_clamp_value,omitempty"` // [H4] the amount actually clamped away
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventTotalSuppliedDustClamp) Reset() {
	*x = EventTotalSuppliedDustClamp{}
	mi := &file_arbor_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTotalSuppliedDustClamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTotalSuppliedDustClamp) ProtoMessage() {}

func (x *EventTotalSuppliedDustClamp) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTotalSuppliedDustClamp.ProtoReflect.Descriptor instead.
func (*EventTotalSuppliedDustClamp) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventTotalSuppliedDustClamp) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventTotalSuppliedDustClamp) GetActualWithdrawn() uint64 {
	if x != nil {
		return x.ActualWithdrawn
	}
	return 0
}

func (x *EventTotalSuppliedDustClamp) GetPreClampValue() uint64 {
	if x != nil {
		return x.PreClampValue
	}
	return 0
}

// EventTotalSharesOutstandingDustClamp fires when a redemption clamps
// total_shares_outstanding to zero
type EventTotalSharesOutstandingDustClamp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MarketId       string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	SharesRedeemed uint64                 `protobuf:"varint,2,opt,name=shares_redeemed,json=sharesRedeemed,proto3" json:"shares_redeemed,omitempty"`
	PreClampValue  uint64                 `protobuf:"varint,3,opt,name=pre_clamp_value,json=preClampValue,proto3" json:"pre_clamp_value,omitempty"` // [H4] the amount actually clamped away
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventTotalSharesOutstandingDustClamp) Reset() {
	*x = EventTotalSharesOutstandingDustClamp{}
	mi := &file_arbor_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTotalSharesOutstandingDustClamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTotalSharesOutstandingDustClamp) ProtoMessage() {}

func (x *EventTotalSharesOutstandingDustClamp) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTotalSharesOutstandingDustClamp.ProtoReflect.Descriptor instead.
func (*EventTotalSharesOutstandingDustClamp) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{3}
}

func (x *EventTotalSharesOutstandingDustClamp) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventTotalSharesOutstandingDustClamp) GetSharesRedeemed() uint64 {
	if x != nil {
		return x.SharesRedeemed
	}
	return 0
}

func (x *EventTotalSharesOutstandingDustClamp) GetPreClampValue() uint64 {
	if x != nil {
		return x.PreClampValue
	}
	return 0
}

// EventTotalBorrowedDustClamp fires when applyDebtDelta's decrement branch
// clamps market.TotalBorrowed to zero because the decrease amount (from
// repay or liquidation) was >= the current aggregate. Mirrors
// EventTotalSuppliedDustClamp's fix (ARCM v3.11.1 Section III.6 / AYIS
// Section 4.4) for the identical failure class on the borrower-side
// aggregate: without this event, the clamp is silent and the resulting
// total_borrowed == 0 (while a position may still show nonzero
// debtPrincipal, per ARCM Invariant I3's drift tolerance) is
// indistinguishable from a market with genuinely no outstanding debt.
type EventTotalBorrowedDustClamp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MarketId       string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                                        // "repay" | "liquidation"
	DecreaseAmount uint64                 `protobuf:"varint,3,opt,name=decrease_amount,json=decreaseAmount,proto3" json:"decrease_amount,omitempty"` // the delta that triggered the clamp
	PreClampValue  uint64                 `protobuf:"varint,4,opt,name=pre_clamp_value,json=preClampValue,proto3" json:"pre_clamp_value,omitempty"`  // the amount actually clamped away
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventTotalBorrowedDustClamp) Reset() {
	*x = EventTotalBorrowedDustClamp{}
	mi := &file_arbor_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTotalBorrowedDustClamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTotalBorrowedDustClamp) ProtoMessage() {}

func (x *EventTotalBorrowedDustClamp) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTotalBorrowedDustClamp.ProtoReflect.Descriptor instead.
func (*EventTotalBorrowedDustClamp) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventTotalBorrowedDustClamp) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventTotalBorrowedDustClamp) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventTotalBorrowedDustClamp) GetDecreaseAmount() uint64 {
	if x != nil {
		return x.DecreaseAmount
	}
	return 0
}

func (x *EventTotalBorrowedDustClamp) GetPreClampValue() uint64 {
	if x != nil {
		return x.PreClampValue
	}
	return 0
}

// EventReserveFundDrawDown fires when Layer2DrawDown fully covers a
// bad-debt shortfall from a market's own R_fund (covered=true only --
// binary gate, bad_debt_layer2.go; no event fires on covered=false,
// consistent with Layer3DrawDown's identical binary-gate contract).
// [RETROACTIVE FIX] Layer2DrawDown has existed and been live since before
// this event was added -- this closes a real observability gap: R_fund
// draw-downs were previously silent on-chain, unlike every other state
// mutation in this file's Layer 4/dust-clamp/migration sections, all of
// which already emit a named event. This is purely additive; it does not
// change Layer2DrawDown's contract, return values, or binary-gate logic.
type EventReserveFundDrawDown struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MarketId             string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	BadDebt              uint64                 `protobuf:"varint,2,opt,name=bad_debt,json=badDebt,proto3" json:"bad_debt,omitempty"`                                         // amount drawn -- == the full shortfall, since binary gate
	RemainingReserveFund string                 `protobuf:"bytes,3,opt,name=remaining_reserve_fund,json=remainingReserveFund,proto3" json:"remaining_reserve_fund,omitempty"` // decimal string, uint128-scale -- R_fund balance after this draw
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EventReserveFundDrawDown) Reset() {
	*x = EventReserveFundDrawDown{}
	mi := &file_arbor_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReserveFundDrawDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReserveFundDrawDown) ProtoMessage() {}

func (x *EventReserveFundDrawDown) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReserveFundDrawDown.ProtoReflect.Descriptor instead.
func (*EventReserveFundDrawDown) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{5}
}

func (x *EventReserveFundDrawDown) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventReserveFundDrawDown) GetBadDebt() uint64 {
	if x != nil {
		return x.BadDebt
	}
	return 0
}

func (x *EventReserveFundDrawDown) GetRemainingReserveFund() string {
	if x != nil {
		return x.RemainingReserveFund
	}
	return ""
}

// EventTreasuryDrawDown fires when Layer3DrawDownArbor or Layer3DrawDownNASM
// fully covers a bad-debt shortfall from its respective T_fund pool
// (covered=true only -- binary gate, bad_debt_layer3.go; no event fires on
// covered=false, matching Layer2DrawDown's own silent-on-miss precedent).
//
// [REVERSED] T_fund was originally a single pool shared by Arbor and
// NASM/NUSD; this event originally had no pool field since there was only
// one pool. Reversed to two isolated pools (see PrefixTreasuryArbor/
// PrefixTreasuryNASM in state_keys.go) -- the pool field below was added
// so an off-chain observer can tell which pool fired, since bad_debt and
// remaining_treasury alone are now ambiguous between the two.
type EventTreasuryDrawDown struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MarketId          string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`                            // the market whose liquidation triggered this draw
	BadDebt           uint64                 `protobuf:"varint,2,opt,name=bad_debt,json=badDebt,proto3" json:"bad_debt,omitempty"`                              // amount drawn -- == the full shortfall, since binary gate
	RemainingTreasury string                 `protobuf:"bytes,3,opt,name=remaining_treasury,json=remainingTreasury,proto3" json:"remaining_treasury,omitempty"` // decimal string, uint128-scale -- T_fund balance after this draw
	Pool              string                 `protobuf:"bytes,4,opt,name=pool,proto3" json:"pool,omitempty"`                                                    // "arbor" | "nasm" -- which isolated T_fund pool this draw came from
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventTreasuryDrawDown) Reset() {
	*x = EventTreasuryDrawDown{}
	mi := &file_arbor_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTreasuryDrawDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTreasuryDrawDown) ProtoMessage() {}

func (x *EventTreasuryDrawDown) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTreasuryDrawDown.ProtoReflect.Descriptor instead.
func (*EventTreasuryDrawDown) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{6}
}

func (x *EventTreasuryDrawDown) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventTreasuryDrawDown) GetBadDebt() uint64 {
	if x != nil {
		return x.BadDebt
	}
	return 0
}

func (x *EventTreasuryDrawDown) GetRemainingTreasury() string {
	if x != nil {
		return x.RemainingTreasury
	}
	return ""
}

func (x *EventTreasuryDrawDown) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

// EventLayer4PendingCountWarning fires when the soft backlog threshold is crossed
type EventLayer4PendingCountWarning struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MarketId            string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	PendingCount        uint32                 `protobuf:"varint,2,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	PendingBadDebtTotal string                 `protobuf:"bytes,3,opt,name=pending_bad_debt_total,json=pendingBadDebtTotal,proto3" json:"pending_bad_debt_total,omitempty"` // decimal string, uint128-scale (L2-widen)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventLayer4PendingCountWarning) Reset() {
	*x = EventLayer4PendingCountWarning{}
	mi := &file_arbor_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLayer4PendingCountWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLayer4PendingCountWarning) ProtoMessage() {}

func (x *EventLayer4PendingCountWarning) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLayer4PendingCountWarning.ProtoReflect.Descriptor instead.
func (*EventLayer4PendingCountWarning) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{7}
}

func (x *EventLayer4PendingCountWarning) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventLayer4PendingCountWarning) GetPendingCount() uint32 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *EventLayer4PendingCountWarning) GetPendingBadDebtTotal() string {
	if x != nil {
		return x.PendingBadDebtTotal
	}
	return ""
}

// EventLayer4PendingBadDebtTotalSaturated fires when the widened uint128 counter
// would overflow (astronomically unlikely post-widen; retained as a tripwire)
type EventLayer4PendingBadDebtTotalSaturated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	BadDebt       uint64                 `protobuf:"varint,2,opt,name=bad_debt,json=badDebt,proto3" json:"bad_debt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLayer4PendingBadDebtTotalSaturated) Reset() {
	*x = EventLayer4PendingBadDebtTotalSaturated{}
	mi := &file_arbor_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLayer4PendingBadDebtTotalSaturated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLayer4PendingBadDebtTotalSaturated) ProtoMessage() {}

func (x *EventLayer4PendingBadDebtTotalSaturated) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLayer4PendingBadDebtTotalSaturated.ProtoReflect.Descriptor instead.
func (*EventLayer4PendingBadDebtTotalSaturated) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{8}
}

func (x *EventLayer4PendingBadDebtTotalSaturated) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventLayer4PendingBadDebtTotalSaturated) GetBadDebt() uint64 {
	if x != nil {
		return x.BadDebt
	}
	return 0
}

// EventLayer4PendingCountUnderflow fires on a decrement-below-zero attempt
// (should never occur; defensive signal only)
type EventLayer4PendingCountUnderflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLayer4PendingCountUnderflow) Reset() {
	*x = EventLayer4PendingCountUnderflow{}
	mi := &file_arbor_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLayer4PendingCountUnderflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLayer4PendingCountUnderflow) ProtoMessage() {}

func (x *EventLayer4PendingCountUnderflow) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLayer4PendingCountUnderflow.ProtoReflect.Descriptor instead.
func (*EventLayer4PendingCountUnderflow) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{9}
}

func (x *EventLayer4PendingCountUnderflow) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

// EventDepositWithdrawBlockedDuringPendingLoss fires when deposit/withdraw/borrow
// is rejected due to layer4_pending_count > 0
type EventDepositWithdrawBlockedDuringPendingLoss struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	TxType        string                 `protobuf:"bytes,2,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDepositWithdrawBlockedDuringPendingLoss) Reset() {
	*x = EventDepositWithdrawBlockedDuringPendingLoss{}
	mi := &file_arbor_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDepositWithdrawBlockedDuringPendingLoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDepositWithdrawBlockedDuringPendingLoss) ProtoMessage() {}

func (x *EventDepositWithdrawBlockedDuringPendingLoss) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDepositWithdrawBlockedDuringPendingLoss.ProtoReflect.Descriptor instead.
func (*EventDepositWithdrawBlockedDuringPendingLoss) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{10}
}

func (x *EventDepositWithdrawBlockedDuringPendingLoss) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventDepositWithdrawBlockedDuringPendingLoss) GetTxType() string {
	if x != nil {
		return x.TxType
	}
	return ""
}

// EventLossFactorExhausted fires when bad_debt >= total_supplied_equiv, driving
// loss_factor to zero and transitioning the market to Insolvent
type EventLossFactorExhausted struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MarketId           string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	BadDebt            uint64                 `protobuf:"varint,2,opt,name=bad_debt,json=badDebt,proto3" json:"bad_debt,omitempty"`
	TotalSuppliedEquiv uint64                 `protobuf:"varint,3,opt,name=total_supplied_equiv,json=totalSuppliedEquiv,proto3" json:"total_supplied_equiv,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EventLossFactorExhausted) Reset() {
	*x = EventLossFactorExhausted{}
	mi := &file_arbor_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLossFactorExhausted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLossFactorExhausted) ProtoMessage() {}

func (x *EventLossFactorExhausted) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLossFactorExhausted.ProtoReflect.Descriptor instead.
func (*EventLossFactorExhausted) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{11}
}

func (x *EventLossFactorExhausted) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventLossFactorExhausted) GetBadDebt() uint64 {
	if x != nil {
		return x.BadDebt
	}
	return 0
}

func (x *EventLossFactorExhausted) GetTotalSuppliedEquiv() uint64 {
	if x != nil {
		return x.TotalSuppliedEquiv
	}
	return 0
}

// EventBadDebtSocialization fires on every non-exhausting Layer 4 haircut application
type EventBadDebtSocialization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	BadDebt       uint64                 `protobuf:"varint,2,opt,name=bad_debt,json=badDebt,proto3" json:"bad_debt,omitempty"`
	NewLossFactor string                 `protobuf:"bytes,3,opt,name=new_loss_factor,json=newLossFactor,proto3" json:"new_loss_factor,omitempty"` // decimal string, uint128-scale, RAY-precision
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBadDebtSocialization) Reset() {
	*x = EventBadDebtSocialization{}
	mi := &file_arbor_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBadDebtSocialization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBadDebtSocialization) ProtoMessage() {}

func (x *EventBadDebtSocialization) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBadDebtSocialization.ProtoReflect.Descriptor instead.
func (*EventBadDebtSocialization) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{12}
}

func (x *EventBadDebtSocialization) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventBadDebtSocialization) GetBadDebt() uint64 {
	if x != nil {
		return x.BadDebt
	}
	return 0
}

func (x *EventBadDebtSocialization) GetNewLossFactor() string {
	if x != nil {
		return x.NewLossFactor
	}
	return ""
}

// EventLossFactorAppliedToAlreadyInsolventMarket fires on the K3 idempotency
// guard's early-return path (queued application against an already-Insolvent market)
type EventLossFactorAppliedToAlreadyInsolventMarket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	BadDebt       uint64                 `protobuf:"varint,2,opt,name=bad_debt,json=badDebt,proto3" json:"bad_debt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLossFactorAppliedToAlreadyInsolventMarket) Reset() {
	*x = EventLossFactorAppliedToAlreadyInsolventMarket{}
	mi := &file_arbor_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLossFactorAppliedToAlreadyInsolventMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLossFactorAppliedToAlreadyInsolventMarket) ProtoMessage() {}

func (x *EventLossFactorAppliedToAlreadyInsolventMarket) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLossFactorAppliedToAlreadyInsolventMarket.ProtoReflect.Descriptor instead.
func (*EventLossFactorAppliedToAlreadyInsolventMarket) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{13}
}

func (x *EventLossFactorAppliedToAlreadyInsolventMarket) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *EventLossFactorAppliedToAlreadyInsolventMarket) GetBadDebt() uint64 {
	if x != nil {
		return x.BadDebt
	}
	return 0
}

// EventReserveFundEncodingMigrationCompleted fires once, at the announced upgrade
// height, after the one-time {18} uint64->uint128 zero-extension pass completes
type EventReserveFundEncodingMigrationCompleted struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CompletedAtHeight uint64                 `protobuf:"varint,1,opt,name=completed_at_height,json=completedAtHeight,proto3" json:"completed_at_height,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventReserveFundEncodingMigrationCompleted) Reset() {
	*x = EventReserveFundEncodingMigrationCompleted{}
	mi := &file_arbor_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReserveFundEncodingMigrationCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReserveFundEncodingMigrationCompleted) ProtoMessage() {}

func (x *EventReserveFundEncodingMigrationCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReserveFundEncodingMigrationCompleted.ProtoReflect.Descriptor instead.
func (*EventReserveFundEncodingMigrationCompleted) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{14}
}

func (x *EventReserveFundEncodingMigrationCompleted) GetCompletedAtHeight() uint64 {
	if x != nil {
		return x.CompletedAtHeight
	}
	return 0
}

// WaterfallEvent is a flat, purpose-built record of one bad-debt waterfall
// step (Layer 2 reserve-fund draw, Layer 3 treasury draw, or Layer 4 lender
// socialization), persisted to the {42} rolling log independently of the
// DeliverTx Event already emitted for that same step (EventReserveFundDrawDown,
// EventTreasuryDrawDown, EventBadDebtSocialization, EventLossFactorExhausted,
// EventLossFactorAppliedToAlreadyInsolventMarket -- see those messages above).
// Deliberately NOT a wrapper around those existing Event/anypb payloads: this
// codebase's DeliverTx Event mechanism has no query surface of its own (Events
// are returned in PluginDeliverResponse and consumed by Canopy core, not
// re-readable from plugin state afterward) -- see apply_loss_factor.go's own
// "EVENT EMISSION, RETURNED NOT EMITTED" doc comment for the identical gap
// this message closes. A flat record avoids re-parsing four different anypb
// payload types on every range-scan read.
type WaterfallEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight uint64                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	MarketId    string                 `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Layer       string                 `protobuf:"bytes,3,opt,name=layer,proto3" json:"layer,omitempty"`                          // "layer2" | "layer3" | "layer4"
	EventType   string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "reserve_fund_draw_down" | "treasury_draw_down" |
	// "bad_debt_socialization" | "loss_factor_exhausted" |
	// "loss_factor_applied_to_already_insolvent_market"
	BadDebt          uint64 `protobuf:"varint,5,opt,name=bad_debt,json=badDebt,proto3" json:"bad_debt,omitempty"`
	RemainingBalance string `protobuf:"bytes,6,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty"` // decimal string -- meaning depends on layer:
	// layer2: R_fund remaining; layer3: T_fund remaining;
	// layer4: new_loss_factor. Empty for the K3
	// idempotency-guard event_type (no balance changed).
	Pool          string `protobuf:"bytes,7,opt,name=pool,proto3" json:"pool,omitempty"` // "arbor" | "nasm" -- layer3 only, empty otherwise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaterfallEvent) Reset() {
	*x = WaterfallEvent{}
	mi := &file_arbor_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaterfallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaterfallEvent) ProtoMessage() {}

func (x *WaterfallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaterfallEvent.ProtoReflect.Descriptor instead.
func (*WaterfallEvent) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{15}
}

func (x *WaterfallEvent) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *WaterfallEvent) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *WaterfallEvent) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *WaterfallEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WaterfallEvent) GetBadDebt() uint64 {
	if x != nil {
		return x.BadDebt
	}
	return 0
}

func (x *WaterfallEvent) GetRemainingBalance() string {
	if x != nil {
		return x.RemainingBalance
	}
	return ""
}

func (x *WaterfallEvent) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

// EventNasmVaultLiquidated fires on every successful liquidate_nasm_vault
// call -- a normal, fully-covered liquidation (collateral_seized <=
// vault.collateral_quantity). Distinct from ARCM's EventBadDebtSocialization
// (which means a Layer 4 lender-haircut application, a different mechanism
// entirely) -- NASM liquidation has no waterfall step of its own yet
// (Phase 1 scope limit, see ErrNasmLiquidationBadDebt), so this event
// reports the liquidation itself, not a waterfall outcome.
type EventNasmVaultLiquidated struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VaultId            string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Liquidator         []byte                 `protobuf:"bytes,2,opt,name=liquidator,proto3" json:"liquidator,omitempty"`
	RepayAmount        uint64                 `protobuf:"varint,3,opt,name=repay_amount,json=repayAmount,proto3" json:"repay_amount,omitempty"`
	CollateralSeized   uint64                 `protobuf:"varint,4,opt,name=collateral_seized,json=collateralSeized,proto3" json:"collateral_seized,omitempty"`
	RemainingVaultDebt uint64                 `protobuf:"varint,5,opt,name=remaining_vault_debt,json=remainingVaultDebt,proto3" json:"remaining_vault_debt,omitempty"` // 0 if the vault was fully closed
	VaultClosed        bool                   `protobuf:"varint,6,opt,name=vault_closed,json=vaultClosed,proto3" json:"vault_closed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EventNasmVaultLiquidated) Reset() {
	*x = EventNasmVaultLiquidated{}
	mi := &file_arbor_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventNasmVaultLiquidated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventNasmVaultLiquidated) ProtoMessage() {}

func (x *EventNasmVaultLiquidated) ProtoReflect() protoreflect.Message {
	mi := &file_arbor_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventNasmVaultLiquidated.ProtoReflect.Descriptor instead.
func (*EventNasmVaultLiquidated) Descriptor() ([]byte, []int) {
	return file_arbor_events_proto_rawDescGZIP(), []int{16}
}

func (x *EventNasmVaultLiquidated) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *EventNasmVaultLiquidated) GetLiquidator() []byte {
	if x != nil {
		return x.Liquidator
	}
	return nil
}

func (x *EventNasmVaultLiquidated) GetRepayAmount() uint64 {
	if x != nil {
		return x.RepayAmount
	}
	return 0
}

func (x *EventNasmVaultLiquidated) GetCollateralSeized() uint64 {
	if x != nil {
		return x.CollateralSeized
	}
	return 0
}

func (x *EventNasmVaultLiquidated) GetRemainingVaultDebt() uint64 {
	if x != nil {
		return x.RemainingVaultDebt
	}
	return 0
}

func (x *EventNasmVaultLiquidated) GetVaultClosed() bool {
	if x != nil {
		return x.VaultClosed
	}
	return false
}

var File_arbor_events_proto protoreflect.FileDescriptor

const file_arbor_events_proto_rawDesc = "" +
	"\n" +
	"\x12arbor_events.proto\x12\x05types\"~\n" +
	" EventIndexEncodingOverflowHalted\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12'\n" +
	"\x0fattempted_value\x18\x03 \x01(\tR\x0eattemptedValue\"\x84\x01\n" +
	"\"EventInsolventMarketValueRecovered\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12)\n" +
	"\x10recovered_amount\x18\x02 \x01(\x04R\x0frecoveredAmount\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\x8d\x01\n" +
	"\x1bEventTotalSuppliedDustClamp\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12)\n" +
	"\x10actual_withdrawn\x18\x02 \x01(\x04R\x0factualWithdrawn\x12&\n" +
	"\x0fpre_clamp_value\x18\x03 \x01(\x04R\rpreClampValue\"\x94\x01\n" +
	"$EventTotalSharesOutstandingDustClamp\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12'\n" +
	"\x0fshares_redeemed\x18\x02 \x01(\x04R\x0esharesRedeemed\x12&\n" +
	"\x0fpre_clamp_value\x18\x03 \x01(\x04R\rpreClampValue\"\xa3\x01\n" +
	"\x1bEventTotalBorrowedDustClamp\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12'\n" +
	"\x0fdecrease_amount\x18\x03 \x01(\x04R\x0edecreaseAmount\x12&\n" +
	"\x0fpre_clamp_value\x18\x04 \x01(\x04R\rpreClampValue\"\x88\x01\n" +
	"\x18EventReserveFundDrawDown\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\bbad_debt\x18\x02 \x01(\x04R\abadDebt\x124\n" +
	"\x16remaining_reserve_fund\x18\x03 \x01(\tR\x14remainingReserveFund\"\x92\x01\n" +
	"\x15EventTreasuryDrawDown\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\bbad_debt\x18\x02 \x01(\x04R\abadDebt\x12-\n" +
	"\x12remaining_treasury\x18\x03 \x01(\tR\x11remainingTreasury\x12\x12\n" +
	"\x04pool\x18\x04 \x01(\tR\x04pool\"\x97\x01\n" +
	"\x1eEventLayer4PendingCountWarning\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12#\n" +
	"\rpending_count\x18\x02 \x01(\rR\fpendingCount\x123\n" +
	"\x16pending_bad_debt_total\x18\x03 \x01(\tR\x13pendingBadDebtTotal\"a\n" +
	"'EventLayer4PendingBadDebtTotalSaturated\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\bbad_debt\x18\x02 \x01(\x04R\abadDebt\"?\n" +
	" EventLayer4PendingCountUnderflow\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\"d\n" +
	",EventDepositWithdrawBlockedDuringPendingLoss\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x17\n" +
	"\atx_type\x18\x02 \x01(\tR\x06txType\"\x84\x01\n" +
	"\x18EventLossFactorExhausted\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\bbad_debt\x18\x02 \x01(\x04R\abadDebt\x120\n" +
	"\x14total_supplied_equiv\x18\x03 \x01(\x04R\x12totalSuppliedEquiv\"{\n" +
	"\x19EventBadDebtSocialization\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\bbad_debt\x18\x02 \x01(\x04R\abadDebt\x12&\n" +
	"\x0fnew_loss_factor\x18\x03 \x01(\tR\rnewLossFactor\"h\n" +
	".EventLossFactorAppliedToAlreadyInsolventMarket\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x19\n" +
	"\bbad_debt\x18\x02 \x01(\x04R\abadDebt\"\\\n" +
	"*EventReserveFundEncodingMigrationCompleted\x12.\n" +
	"\x13completed_at_height\x18\x01 \x01(\x04R\x11completedAtHeight\"\xe1\x01\n" +
	"\x0eWaterfallEvent\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x12\x14\n" +
	"\x05layer\x18\x03 \x01(\tR\x05layer\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x19\n" +
	"\bbad_debt\x18\x05 \x01(\x04R\abadDebt\x12+\n" +
	"\x11remaining_balance\x18\x06 \x01(\tR\x10remainingBalance\x12\x12\n" +
	"\x04pool\x18\a \x01(\tR\x04pool\"\xfa\x01\n" +
	"\x18EventNasmVaultLiquidated\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x1e\n" +
	"\n" +
	"liquidator\x18\x02 \x01(\fR\n" +
	"liquidator\x12!\n" +
	"\frepay_amount\x18\x03 \x01(\x04R\vrepayAmount\x12+\n" +
	"\x11collateral_seized\x18\x04 \x01(\x04R\x10collateralSeized\x120\n" +
	"\x14remaining_vault_debt\x18\x05 \x01(\x04R\x12remainingVaultDebt\x12!\n" +
	"\fvault_closed\x18\x06 \x01(\bR\vvaultClosedB-Z+github.com/ARBOR-L/ARBOR/plugin/go/contractb\x06proto3"

var (
	file_arbor_events_proto_rawDescOnce sync.Once
	file_arbor_events_proto_rawDescData []byte
)

func file_arbor_events_proto_rawDescGZIP() []byte {
	file_arbor_events_proto_rawDescOnce.Do(func() {
		file_arbor_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arbor_events_proto_rawDesc), len(file_arbor_events_proto_rawDesc)))
	})
	return file_arbor_events_proto_rawDescData
}

var file_arbor_events_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_arbor_events_proto_goTypes = []any{
	(*EventIndexEncodingOverflowHalted)(nil),               // 0: types.EventIndexEncodingOverflowHalted
	(*EventInsolventMarketValueRecovered)(nil),             // 1: types.EventInsolventMarketValueRecovered
	(*EventTotalSuppliedDustClamp)(nil),                    // 2: types.EventTotalSuppliedDustClamp
	(*EventTotalSharesOutstandingDustClamp)(nil),           // 3: types.EventTotalSharesOutstandingDustClamp
	(*EventTotalBorrowedDustClamp)(nil),                    // 4: types.EventTotalBorrowedDustClamp
	(*EventReserveFundDrawDown)(nil),                       // 5: types.EventReserveFundDrawDown
	(*EventTreasuryDrawDown)(nil),                          // 6: types.EventTreasuryDrawDown
	(*EventLayer4PendingCountWarning)(nil),                 // 7: types.EventLayer4PendingCountWarning
	(*EventLayer4PendingBadDebtTotalSaturated)(nil),        // 8: types.EventLayer4PendingBadDebtTotalSaturated
	(*EventLayer4PendingCountUnderflow)(nil),               // 9: types.EventLayer4PendingCountUnderflow
	(*EventDepositWithdrawBlockedDuringPendingLoss)(nil),   // 10: types.EventDepositWithdrawBlockedDuringPendingLoss
	(*EventLossFactorExhausted)(nil),                       // 11: types.EventLossFactorExhausted
	(*EventBadDebtSocialization)(nil),                      // 12: types.EventBadDebtSocialization
	(*EventLossFactorAppliedToAlreadyInsolventMarket)(nil), // 13: types.EventLossFactorAppliedToAlreadyInsolventMarket
	(*EventReserveFundEncodingMigrationCompleted)(nil),     // 14: types.EventReserveFundEncodingMigrationCompleted
	(*WaterfallEvent)(nil),                                 // 15: types.WaterfallEvent
	(*EventNasmVaultLiquidated)(nil),                       // 16: types.EventNasmVaultLiquidated
}
var file_arbor_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arbor_events_proto_init() }
func file_arbor_events_proto_init() {
	if File_arbor_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arbor_events_proto_rawDesc), len(file_arbor_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_arbor_events_proto_goTypes,
		DependencyIndexes: file_arbor_events_proto_depIdxs,
		MessageInfos:      file_arbor_events_proto_msgTypes,
	}.Build()
	File_arbor_events_proto = out.File
	file_arbor_events_proto_goTypes = nil
	file_arbor_events_proto_depIdxs = nil
}
