// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: tx.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction represents a request or action submitted to the network like transfer assets or perform other operations
// within the blockchain system - THIS MUST MATCH lib.Transaction EXACTLY for signing
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type: The type of the transaction like 'send' or 'stake'
	MessageType string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"messageType"` // @gotags: json:"messageType"
	// msg: The actual transaction message payload, which is encapsulated in a generic message format
	Msg *anypb.Any `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// signature: The cryptographic signature used to verify the authenticity of the transaction
	Signature *Signature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// created_height: The height when the transaction was created - allows 'safe pruning'
	CreatedHeight uint64 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	// time: The timestamp when the transaction was created - used as temporal entropy to prevent hash collisions in txs
	Time uint64 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	// fee: The fee associated with processing the transaction
	Fee uint64 `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	// memo: An optional message or note attached to the transaction
	Memo string `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	// network_id: The identity of the network the transaction is intended for
	NetworkId uint64 `protobuf:"varint,8,opt,name=network_id,json=networkId,proto3" json:"networkID"` // @gotags: json:"networkID"
	// chain_id: The identity of the committee the transaction is intended for
	ChainId       uint64 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chainID"` // @gotags: json:"chainID"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Transaction) GetMsg() *anypb.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Transaction) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Transaction) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// MessageSend is a standard transfer transaction, taking tokens from the sender and transferring
// them to the recipient
type MessageSend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from_address: is the sender of the funds
	FromAddress []byte `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"fromAddress"` // @gotags: json:"fromAddress"
	// to_address: is the recipient of the funds
	ToAddress []byte `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"toAddress"` // @gotags: json:"toAddress"
	// amount: is the amount of tokens in micro-denomination (uKNBT)
	Amount        uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSend) Reset() {
	*x = MessageSend{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSend) ProtoMessage() {}

func (x *MessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSend.ProtoReflect.Descriptor instead.
func (*MessageSend) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MessageSend) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageSend) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *MessageSend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// MessageBetCreate creates a new betting question.
// The creator must stake a minimum of 100 KNBT (100,000,000 uknbt)
// and pre-commit the answer as a SHA-256 hash for trustless reveal.
type MessageBetCreate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// creator_address: the address of the question creator (20 bytes)
	CreatorAddress []byte `protobuf:"bytes,1,opt,name=creator_address,json=creatorAddress,proto3" json:"creatorAddress"` // @gotags: json:"creatorAddress"
	// question_text: the betting question text (e.g. "BTC > $100k on 2026-12-31?")
	QuestionText string `protobuf:"bytes,2,opt,name=question_text,json=questionText,proto3" json:"questionText"` // @gotags: json:"questionText"
	// options: the possible answer choices (2-5 options)
	Options []string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	// answer_hash: SHA-256 hash of the correct answer, hex-encoded
	// The creator pre-commits the answer hash so they cannot change it later.
	AnswerHash string `protobuf:"bytes,4,opt,name=answer_hash,json=answerHash,proto3" json:"answerHash"` // @gotags: json:"answerHash"
	// stake_amount: the amount locked by the creator as a good-faith stake (in uknbt)
	StakeAmount uint64 `protobuf:"varint,5,opt,name=stake_amount,json=stakeAmount,proto3" json:"stakeAmount"` // @gotags: json:"stakeAmount"
	// duration: the betting period in seconds before the question closes.
	// After this period, no more bets can be placed.
	Duration      int64 `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBetCreate) Reset() {
	*x = MessageBetCreate{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBetCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBetCreate) ProtoMessage() {}

func (x *MessageBetCreate) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBetCreate.ProtoReflect.Descriptor instead.
func (*MessageBetCreate) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MessageBetCreate) GetCreatorAddress() []byte {
	if x != nil {
		return x.CreatorAddress
	}
	return nil
}

func (x *MessageBetCreate) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *MessageBetCreate) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MessageBetCreate) GetAnswerHash() string {
	if x != nil {
		return x.AnswerHash
	}
	return ""
}

func (x *MessageBetCreate) GetStakeAmount() uint64 {
	if x != nil {
		return x.StakeAmount
	}
	return 0
}

func (x *MessageBetCreate) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// MessageBetPlace places a bet on a specific option of a question.
type MessageBetPlace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// participant_address: the address of the participant placing the bet (20 bytes)
	ParticipantAddress []byte `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participantAddress"` // @gotags: json:"participantAddress"
	// question_id: the unique ID of the question to bet on
	QuestionId uint64 `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"questionId"` // @gotags: json:"questionId"
	// option_index: the index of the chosen option (0-based)
	OptionIndex uint32 `protobuf:"varint,3,opt,name=option_index,json=optionIndex,proto3" json:"optionIndex"` // @gotags: json:"optionIndex"
	// amount: the amount to bet (in uknbt, range 10-10000 KNBT)
	Amount        uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBetPlace) Reset() {
	*x = MessageBetPlace{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBetPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBetPlace) ProtoMessage() {}

func (x *MessageBetPlace) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBetPlace.ProtoReflect.Descriptor instead.
func (*MessageBetPlace) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MessageBetPlace) GetParticipantAddress() []byte {
	if x != nil {
		return x.ParticipantAddress
	}
	return nil
}

func (x *MessageBetPlace) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *MessageBetPlace) GetOptionIndex() uint32 {
	if x != nil {
		return x.OptionIndex
	}
	return 0
}

func (x *MessageBetPlace) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// MessageBetReveal reveals the answer to a question.
// Only the question creator can reveal the answer.
// The revealed answer is verified against the pre-committed SHA-256 hash.
type MessageBetReveal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// revealer_address: the address revealing the answer (must be the creator, 20 bytes)
	RevealerAddress []byte `protobuf:"bytes,1,opt,name=revealer_address,json=revealerAddress,proto3" json:"revealerAddress"` // @gotags: json:"revealerAddress"
	// question_id: the unique ID of the question
	QuestionId uint64 `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"questionId"` // @gotags: json:"questionId"
	// answer: the plaintext answer that matches one of the options
	Answer        string `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBetReveal) Reset() {
	*x = MessageBetReveal{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBetReveal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBetReveal) ProtoMessage() {}

func (x *MessageBetReveal) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBetReveal.ProtoReflect.Descriptor instead.
func (*MessageBetReveal) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MessageBetReveal) GetRevealerAddress() []byte {
	if x != nil {
		return x.RevealerAddress
	}
	return nil
}

func (x *MessageBetReveal) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *MessageBetReveal) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// MessageBetSettle settles a question after the answer has been revealed.
// Distributes the prize pool: 80% to winners, 15% to question creator, 5% burned.
// This can be called by anyone after the answer is revealed.
type MessageBetSettle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// question_id: the unique ID of the question to settle
	QuestionId    uint64 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"questionId"` // @gotags: json:"questionId"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBetSettle) Reset() {
	*x = MessageBetSettle{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBetSettle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBetSettle) ProtoMessage() {}

func (x *MessageBetSettle) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBetSettle.ProtoReflect.Descriptor instead.
func (*MessageBetSettle) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MessageBetSettle) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

// MessageBetRefund triggers an automatic refund for an expired question.
// If the creator does not reveal within 7 days (604800 seconds) of question close,
// all bets are refunded to the participants and the creator's stake is burned.
type MessageBetRefund struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// question_id: the unique ID of the question to refund
	QuestionId    uint64 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"questionId"` // @gotags: json:"questionId"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBetRefund) Reset() {
	*x = MessageBetRefund{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBetRefund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBetRefund) ProtoMessage() {}

func (x *MessageBetRefund) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBetRefund.ProtoReflect.Descriptor instead.
func (*MessageBetRefund) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MessageBetRefund) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

// Question stores the on-chain state of a betting question.
type Question struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id: the unique question ID
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// creator_address: the address that created this question (20 bytes)
	CreatorAddress []byte `protobuf:"bytes,2,opt,name=creator_address,json=creatorAddress,proto3" json:"creatorAddress"` // @gotags: json:"creatorAddress"
	// question_text: the betting question
	QuestionText string `protobuf:"bytes,3,opt,name=question_text,json=questionText,proto3" json:"questionText"` // @gotags: json:"questionText"
	// options: the possible answer choices
	Options []string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	// answer_hash: SHA-256 hash of the correct answer, hex-encoded
	AnswerHash string `protobuf:"bytes,5,opt,name=answer_hash,json=answerHash,proto3" json:"answerHash"` // @gotags: json:"answerHash"
	// stake_amount: the creator's locked stake (in uknbt)
	StakeAmount uint64 `protobuf:"varint,6,opt,name=stake_amount,json=stakeAmount,proto3" json:"stakeAmount"` // @gotags: json:"stakeAmount"
	// total_pool: the total amount in the prize pool (all bets + stake, in uknbt)
	TotalPool uint64 `protobuf:"varint,7,opt,name=total_pool,json=totalPool,proto3" json:"totalPool"` // @gotags: json:"totalPool"
	// option_pools: accumulated bets per option index (index matches options order)
	OptionPools []uint64 `protobuf:"varint,8,rep,packed,name=option_pools,json=optionPools,proto3" json:"optionPools"` // @gotags: json:"optionPools"
	// created_height: the block height when the question was created
	CreatedHeight uint64 `protobuf:"varint,9,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	// close_time: the unix timestamp (in seconds) when betting closes
	CloseTime int64 `protobuf:"varint,10,opt,name=close_time,json=closeTime,proto3" json:"closeTime"` // @gotags: json:"closeTime"
	// revealed: whether the answer has been revealed
	Revealed bool `protobuf:"varint,11,opt,name=revealed,proto3" json:"revealed,omitempty"`
	// revealed_answer: the revealed answer text, empty if not yet revealed
	RevealedAnswer string `protobuf:"bytes,12,opt,name=revealed_answer,json=revealedAnswer,proto3" json:"revealedAnswer"` // @gotags: json:"revealedAnswer"
	// settled: whether the question has been settled
	Settled bool `protobuf:"varint,13,opt,name=settled,proto3" json:"settled,omitempty"`
	// refunded: whether the question has been refunded
	Refunded bool `protobuf:"varint,14,opt,name=refunded,proto3" json:"refunded,omitempty"`
	// close_height: the block height when betting closes
	CloseHeight uint64 `protobuf:"varint,15,opt,name=close_height,json=closeHeight,proto3" json:"closeHeight"` // @gotags: json:"closeHeight"
	// participant_addresses: list of all participant addresses for refund/settlement iteration
	ParticipantAddresses [][]byte `protobuf:"bytes,16,rep,name=participant_addresses,json=participantAddresses,proto3" json:"participantAddresses"` // @gotags: json:"participantAddresses"
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

func (x *Question) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Question) GetCreatorAddress() []byte {
	if x != nil {
		return x.CreatorAddress
	}
	return nil
}

func (x *Question) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetAnswerHash() string {
	if x != nil {
		return x.AnswerHash
	}
	return ""
}

func (x *Question) GetStakeAmount() uint64 {
	if x != nil {
		return x.StakeAmount
	}
	return 0
}

func (x *Question) GetTotalPool() uint64 {
	if x != nil {
		return x.TotalPool
	}
	return 0
}

func (x *Question) GetOptionPools() []uint64 {
	if x != nil {
		return x.OptionPools
	}
	return nil
}

func (x *Question) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Question) GetCloseTime() int64 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

func (x *Question) GetRevealed() bool {
	if x != nil {
		return x.Revealed
	}
	return false
}

func (x *Question) GetRevealedAnswer() string {
	if x != nil {
		return x.RevealedAnswer
	}
	return ""
}

func (x *Question) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

func (x *Question) GetRefunded() bool {
	if x != nil {
		return x.Refunded
	}
	return false
}

func (x *Question) GetCloseHeight() uint64 {
	if x != nil {
		return x.CloseHeight
	}
	return 0
}

func (x *Question) GetParticipantAddresses() [][]byte {
	if x != nil {
		return x.ParticipantAddresses
	}
	return nil
}

// BetRecord stores an individual participant's bet on a question.
type BetRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// participant_address: the address of the participant (20 bytes)
	ParticipantAddress []byte `protobuf:"bytes,1,opt,name=participant_address,json=participantAddress,proto3" json:"participantAddress"` // @gotags: json:"participantAddress"
	// question_id: the question this bet belongs to
	QuestionId uint64 `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"questionId"` // @gotags: json:"questionId"
	// option_index: which option was bet on (0-based)
	OptionIndex uint32 `protobuf:"varint,3,opt,name=option_index,json=optionIndex,proto3" json:"optionIndex"` // @gotags: json:"optionIndex"
	// amount: the amount bet (in uknbt)
	Amount        uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetRecord) Reset() {
	*x = BetRecord{}
	mi := &file_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetRecord) ProtoMessage() {}

func (x *BetRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetRecord.ProtoReflect.Descriptor instead.
func (*BetRecord) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *BetRecord) GetParticipantAddress() []byte {
	if x != nil {
		return x.ParticipantAddress
	}
	return nil
}

func (x *BetRecord) GetQuestionId() uint64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *BetRecord) GetOptionIndex() uint32 {
	if x != nil {
		return x.OptionIndex
	}
	return 0
}

func (x *BetRecord) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// FeeParams is the parameter space that defines various amounts for transaction fees
type FeeParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// send_fee: is the fee amount (in uknbt) for Message Send
	SendFee uint64 `protobuf:"varint,1,opt,name=send_fee,json=sendFee,proto3" json:"sendFee"` // @gotags: json:"sendFee"
	// bet_create_fee: fee for MessageBetCreate
	BetCreateFee uint64 `protobuf:"varint,2,opt,name=bet_create_fee,json=betCreateFee,proto3" json:"betCreateFee"` // @gotags: json:"betCreateFee"
	// bet_place_fee: fee for MessageBetPlace
	BetPlaceFee uint64 `protobuf:"varint,3,opt,name=bet_place_fee,json=betPlaceFee,proto3" json:"betPlaceFee"` // @gotags: json:"betPlaceFee"
	// bet_reveal_fee: fee for MessageBetReveal
	BetRevealFee uint64 `protobuf:"varint,4,opt,name=bet_reveal_fee,json=betRevealFee,proto3" json:"betRevealFee"` // @gotags: json:"betRevealFee"
	// bet_settle_fee: fee for MessageBetSettle
	BetSettleFee uint64 `protobuf:"varint,5,opt,name=bet_settle_fee,json=betSettleFee,proto3" json:"betSettleFee"` // @gotags: json:"betSettleFee"
	// bet_refund_fee: fee for MessageBetRefund
	BetRefundFee  uint64 `protobuf:"varint,6,opt,name=bet_refund_fee,json=betRefundFee,proto3" json:"betRefundFee"` // @gotags: json:"betRefundFee"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeParams) Reset() {
	*x = FeeParams{}
	mi := &file_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeParams) ProtoMessage() {}

func (x *FeeParams) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeParams.ProtoReflect.Descriptor instead.
func (*FeeParams) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

func (x *FeeParams) GetSendFee() uint64 {
	if x != nil {
		return x.SendFee
	}
	return 0
}

func (x *FeeParams) GetBetCreateFee() uint64 {
	if x != nil {
		return x.BetCreateFee
	}
	return 0
}

func (x *FeeParams) GetBetPlaceFee() uint64 {
	if x != nil {
		return x.BetPlaceFee
	}
	return 0
}

func (x *FeeParams) GetBetRevealFee() uint64 {
	if x != nil {
		return x.BetRevealFee
	}
	return 0
}

func (x *FeeParams) GetBetSettleFee() uint64 {
	if x != nil {
		return x.BetSettleFee
	}
	return 0
}

func (x *FeeParams) GetBetRefundFee() uint64 {
	if x != nil {
		return x.BetRefundFee
	}
	return 0
}

// A Signature is a digital signature is a cryptographic "fingerprint" created with a private key,
// allowing others to verify the authenticity and integrity of a message using the corresponding public key
type Signature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// public_key: is a cryptographic code shared openly, used to verify digital signatures
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"publicKey"` // @gotags: json:"publicKey"
	// signature: the bytes of the signature output from a private key which may be verified with the message and public
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\xa3\x02\n" +
	"\vTransaction\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12&\n" +
	"\x03msg\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03msg\x12.\n" +
	"\tsignature\x18\x03 \x01(\v2\x10.types.SignatureR\tsignature\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x04R\x03fee\x12\x12\n" +
	"\x04memo\x18\a \x01(\tR\x04memo\x12\x1d\n" +
	"\n" +
	"network_id\x18\b \x01(\x04R\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\"g\n" +
	"\vMessageSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\fR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\fR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"\xda\x01\n" +
	"\x10MessageBetCreate\x12'\n" +
	"\x0fcreator_address\x18\x01 \x01(\fR\x0ecreatorAddress\x12#\n" +
	"\rquestion_text\x18\x02 \x01(\tR\fquestionText\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12\x1f\n" +
	"\vanswer_hash\x18\x04 \x01(\tR\n" +
	"answerHash\x12!\n" +
	"\fstake_amount\x18\x05 \x01(\x04R\vstakeAmount\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x03R\bduration\"\x9e\x01\n" +
	"\x0fMessageBetPlace\x12/\n" +
	"\x13participant_address\x18\x01 \x01(\fR\x12participantAddress\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x04R\n" +
	"questionId\x12!\n" +
	"\foption_index\x18\x03 \x01(\rR\voptionIndex\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\"v\n" +
	"\x10MessageBetReveal\x12)\n" +
	"\x10revealer_address\x18\x01 \x01(\fR\x0frevealerAddress\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x04R\n" +
	"questionId\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\"3\n" +
	"\x10MessageBetSettle\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\"3\n" +
	"\x10MessageBetRefund\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x04R\n" +
	"questionId\"\xa1\x04\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12'\n" +
	"\x0fcreator_address\x18\x02 \x01(\fR\x0ecreatorAddress\x12#\n" +
	"\rquestion_text\x18\x03 \x01(\tR\fquestionText\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12\x1f\n" +
	"\vanswer_hash\x18\x05 \x01(\tR\n" +
	"answerHash\x12!\n" +
	"\fstake_amount\x18\x06 \x01(\x04R\vstakeAmount\x12\x1d\n" +
	"\n" +
	"total_pool\x18\a \x01(\x04R\ttotalPool\x12!\n" +
	"\foption_pools\x18\b \x03(\x04R\voptionPools\x12%\n" +
	"\x0ecreated_height\x18\t \x01(\x04R\rcreatedHeight\x12\x1d\n" +
	"\n" +
	"close_time\x18\n" +
	" \x01(\x03R\tcloseTime\x12\x1a\n" +
	"\brevealed\x18\v \x01(\bR\brevealed\x12'\n" +
	"\x0frevealed_answer\x18\f \x01(\tR\x0erevealedAnswer\x12\x18\n" +
	"\asettled\x18\r \x01(\bR\asettled\x12\x1a\n" +
	"\brefunded\x18\x0e \x01(\bR\brefunded\x12!\n" +
	"\fclose_height\x18\x0f \x01(\x04R\vcloseHeight\x123\n" +
	"\x15participant_addresses\x18\x10 \x03(\fR\x14participantAddresses\"\x98\x01\n" +
	"\tBetRecord\x12/\n" +
	"\x13participant_address\x18\x01 \x01(\fR\x12participantAddress\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x04R\n" +
	"questionId\x12!\n" +
	"\foption_index\x18\x03 \x01(\rR\voptionIndex\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\"\xe2\x01\n" +
	"\tFeeParams\x12\x19\n" +
	"\bsend_fee\x18\x01 \x01(\x04R\asendFee\x12$\n" +
	"\x0ebet_create_fee\x18\x02 \x01(\x04R\fbetCreateFee\x12\"\n" +
	"\rbet_place_fee\x18\x03 \x01(\x04R\vbetPlaceFee\x12$\n" +
	"\x0ebet_reveal_fee\x18\x04 \x01(\x04R\fbetRevealFee\x12$\n" +
	"\x0ebet_settle_fee\x18\x05 \x01(\x04R\fbetSettleFee\x12$\n" +
	"\x0ebet_refund_fee\x18\x06 \x01(\x04R\fbetRefundFee\"H\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignatureB.Z,github.com/canopy-network/go-plugin/contractb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tx_proto_goTypes = []any{
	(*Transaction)(nil),      // 0: types.Transaction
	(*MessageSend)(nil),      // 1: types.MessageSend
	(*MessageBetCreate)(nil), // 2: types.MessageBetCreate
	(*MessageBetPlace)(nil),  // 3: types.MessageBetPlace
	(*MessageBetReveal)(nil), // 4: types.MessageBetReveal
	(*MessageBetSettle)(nil), // 5: types.MessageBetSettle
	(*MessageBetRefund)(nil), // 6: types.MessageBetRefund
	(*Question)(nil),         // 7: types.Question
	(*BetRecord)(nil),        // 8: types.BetRecord
	(*FeeParams)(nil),        // 9: types.FeeParams
	(*Signature)(nil),        // 10: types.Signature
	(*anypb.Any)(nil),        // 11: google.protobuf.Any
}
var file_tx_proto_depIdxs = []int32{
	11, // 0: types.Transaction.msg:type_name -> google.protobuf.Any
	10, // 1: types.Transaction.signature:type_name -> types.Signature
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
