// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: tx.proto

// package must match plugin.proto imports

package contract

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Msg           *any1.Any              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Signature     *Signature             `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedHeight uint64                 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	Time          uint64                 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	Fee           uint64                 `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	Memo          string                 `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	NetworkId     uint64                 `protobuf:"varint,8,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	ChainId       uint64                 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Transaction) GetMsg() *any1.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Transaction) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Transaction) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

type FeeParams struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SendFee             uint64                 `protobuf:"varint,1,opt,name=send_fee,json=sendFee,proto3" json:"send_fee,omitempty"`
	CreateMarketFee     uint64                 `protobuf:"varint,2,opt,name=create_market_fee,json=createMarketFee,proto3" json:"create_market_fee,omitempty"`
	SubmitPredictionFee uint64                 `protobuf:"varint,3,opt,name=submit_prediction_fee,json=submitPredictionFee,proto3" json:"submit_prediction_fee,omitempty"`
	ResolveMarketFee    uint64                 `protobuf:"varint,4,opt,name=resolve_market_fee,json=resolveMarketFee,proto3" json:"resolve_market_fee,omitempty"`
	ClaimWinningsFee    uint64                 `protobuf:"varint,5,opt,name=claim_winnings_fee,json=claimWinningsFee,proto3" json:"claim_winnings_fee,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FeeParams) Reset() {
	*x = FeeParams{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeParams) ProtoMessage() {}

func (x *FeeParams) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeParams.ProtoReflect.Descriptor instead.
func (*FeeParams) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *FeeParams) GetSendFee() uint64 {
	if x != nil {
		return x.SendFee
	}
	return 0
}

func (x *FeeParams) GetCreateMarketFee() uint64 {
	if x != nil {
		return x.CreateMarketFee
	}
	return 0
}

func (x *FeeParams) GetSubmitPredictionFee() uint64 {
	if x != nil {
		return x.SubmitPredictionFee
	}
	return 0
}

func (x *FeeParams) GetResolveMarketFee() uint64 {
	if x != nil {
		return x.ResolveMarketFee
	}
	return 0
}

func (x *FeeParams) GetClaimWinningsFee() uint64 {
	if x != nil {
		return x.ClaimWinningsFee
	}
	return 0
}

// ═══════════════════════════════════════════════════════════════════════════
// CANOPY BASE LAYER — send only (the plugin owns its internal token economy)
// ═══════════════════════════════════════════════════════════════════════════
type MessageSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   []byte                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"` // 20 bytes
	ToAddress     []byte                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`       // 20 bytes
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSend) Reset() {
	*x = MessageSend{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSend) ProtoMessage() {}

func (x *MessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSend.ProtoReflect.Descriptor instead.
func (*MessageSend) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MessageSend) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageSend) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *MessageSend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// ═══════════════════════════════════════════════════════════════════════════
// PRAXIS ADLMSR — core prediction market (Phase 1 — indices 1–4)
// Spec: ADLMSR v5.6.6-r2-CORRECTED
// ═══════════════════════════════════════════════════════════════════════════
// create_market — index 1
// Spec §CreateMarket. Fields: creator_address, b0, expiry_time, nonce, question
// CRIT: no resolver_address here — resolver is the PORS system
type MessageCreateMarket struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CreatorAddress []byte                 `protobuf:"bytes,1,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"` // 20 bytes
	B0             uint64                 `protobuf:"varint,2,opt,name=b0,proto3" json:"b0,omitempty"`                                              // initial LMSR liquidity parameter (min MIN_B0)
	ExpiryTime     uint64                 `protobuf:"varint,3,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`            // block height when market expires (guarded by MAX_EXPIRY_TIME)
	Nonce          uint64                 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`                                        // nonce for market_id derivation — must be nonzero
	Question       string                 `protobuf:"bytes,5,opt,name=question,proto3" json:"question,omitempty"`                                   // human-readable question
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageCreateMarket) Reset() {
	*x = MessageCreateMarket{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreateMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreateMarket) ProtoMessage() {}

func (x *MessageCreateMarket) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreateMarket.ProtoReflect.Descriptor instead.
func (*MessageCreateMarket) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MessageCreateMarket) GetCreatorAddress() []byte {
	if x != nil {
		return x.CreatorAddress
	}
	return nil
}

func (x *MessageCreateMarket) GetB0() uint64 {
	if x != nil {
		return x.B0
	}
	return 0
}

func (x *MessageCreateMarket) GetExpiryTime() uint64 {
	if x != nil {
		return x.ExpiryTime
	}
	return 0
}

func (x *MessageCreateMarket) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *MessageCreateMarket) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

// submit_prediction — index 2
// Spec §SubmitPrediction. AUDIT-3/5/7/12 fixes applied in DeliverTx handler.
type MessageSubmitPrediction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      []byte                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`                // 20 bytes — SHA256(creator_addr + nonce)[:20]
	BettorAddress []byte                 `protobuf:"bytes,2,opt,name=bettor_address,json=bettorAddress,proto3" json:"bettor_address,omitempty"` // 20 bytes — also the signer
	Outcome       bool                   `protobuf:"varint,3,opt,name=outcome,proto3" json:"outcome,omitempty"`                                 // true = YES, false = NO
	Shares        uint64                 `protobuf:"varint,4,opt,name=shares,proto3" json:"shares,omitempty"`                                   // must be >= PRECISION_SCALE in DeliverTx (AUDIT-7)
	MaxCost       uint64                 `protobuf:"varint,5,opt,name=max_cost,json=maxCost,proto3" json:"max_cost,omitempty"`                  // slippage cap — DeliverTx rejects if cost > max_cost (AUDIT-12)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSubmitPrediction) Reset() {
	*x = MessageSubmitPrediction{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSubmitPrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSubmitPrediction) ProtoMessage() {}

func (x *MessageSubmitPrediction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSubmitPrediction.ProtoReflect.Descriptor instead.
func (*MessageSubmitPrediction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MessageSubmitPrediction) GetMarketId() []byte {
	if x != nil {
		return x.MarketId
	}
	return nil
}

func (x *MessageSubmitPrediction) GetBettorAddress() []byte {
	if x != nil {
		return x.BettorAddress
	}
	return nil
}

func (x *MessageSubmitPrediction) GetOutcome() bool {
	if x != nil {
		return x.Outcome
	}
	return false
}

func (x *MessageSubmitPrediction) GetShares() uint64 {
	if x != nil {
		return x.Shares
	}
	return 0
}

func (x *MessageSubmitPrediction) GetMaxCost() uint64 {
	if x != nil {
		return x.MaxCost
	}
	return 0
}

// resolve_market — index 3
// Spec §ResolveMarket. Auth before idempotency (R1 fix). 6-key atomic write (NEW-1).
type MessageResolveMarket struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarketId        []byte                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`                      // 20 bytes
	ResolverAddress []byte                 `protobuf:"bytes,2,opt,name=resolver_address,json=resolverAddress,proto3" json:"resolver_address,omitempty"` // 20 bytes — must match 0x13 ResolverState
	WinningOutcome  bool                   `protobuf:"varint,3,opt,name=winning_outcome,json=winningOutcome,proto3" json:"winning_outcome,omitempty"`   // true = YES wins, false = NO wins
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageResolveMarket) Reset() {
	*x = MessageResolveMarket{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResolveMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResolveMarket) ProtoMessage() {}

func (x *MessageResolveMarket) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResolveMarket.ProtoReflect.Descriptor instead.
func (*MessageResolveMarket) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MessageResolveMarket) GetMarketId() []byte {
	if x != nil {
		return x.MarketId
	}
	return nil
}

func (x *MessageResolveMarket) GetResolverAddress() []byte {
	if x != nil {
		return x.ResolverAddress
	}
	return nil
}

func (x *MessageResolveMarket) GetWinningOutcome() bool {
	if x != nil {
		return x.WinningOutcome
	}
	return false
}

// claim_winnings — index 4
// Spec §ClaimWinnings. Gates on STATUS_FINALIZED=6 (CRIT-2 fix). 4-key atomic write.
type MessageClaimWinnings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarketId        []byte                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`                      // 20 bytes
	ClaimantAddress []byte                 `protobuf:"bytes,2,opt,name=claimant_address,json=claimantAddress,proto3" json:"claimant_address,omitempty"` // 20 bytes — validated in CheckTx (R6 fix)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageClaimWinnings) Reset() {
	*x = MessageClaimWinnings{}
	mi := &file_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageClaimWinnings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageClaimWinnings) ProtoMessage() {}

func (x *MessageClaimWinnings) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageClaimWinnings.ProtoReflect.Descriptor instead.
func (*MessageClaimWinnings) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MessageClaimWinnings) GetMarketId() []byte {
	if x != nil {
		return x.MarketId
	}
	return nil
}

func (x *MessageClaimWinnings) GetClaimantAddress() []byte {
	if x != nil {
		return x.ClaimantAddress
	}
	return nil
}

// ═══════════════════════════════════════════════════════════════════════════
// PRAXIS PORS — resolver & dispute system (Phase 2 — indices 5–11)
// Spec: PORS v1.0-r2-CORRECTED
// ═══════════════════════════════════════════════════════════════════════════
// register_resolver — index 5
// Spec PORS §RegisterResolver.
type MessageRegisterResolver struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResolverAddress []byte                 `protobuf:"bytes,1,opt,name=resolver_address,json=resolverAddress,proto3" json:"resolver_address,omitempty"` // 20 bytes — BLS address
	StakeAmount     uint64                 `protobuf:"varint,2,opt,name=stake_amount,json=stakeAmount,proto3" json:"stake_amount,omitempty"`            // PRX to stake (min MIN_RESOLVER_STAKE)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageRegisterResolver) Reset() {
	*x = MessageRegisterResolver{}
	mi := &file_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRegisterResolver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRegisterResolver) ProtoMessage() {}

func (x *MessageRegisterResolver) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRegisterResolver.ProtoReflect.Descriptor instead.
func (*MessageRegisterResolver) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MessageRegisterResolver) GetResolverAddress() []byte {
	if x != nil {
		return x.ResolverAddress
	}
	return nil
}

func (x *MessageRegisterResolver) GetStakeAmount() uint64 {
	if x != nil {
		return x.StakeAmount
	}
	return 0
}

// propose_outcome — index 6
// Spec PORS §ProposeOutcome. NF-5: writes 0x13 as 4th atomic key.
// NF-6: accepts STATUS_OPEN if now > ExpiryTime (inline transition, EXPIRED never persisted).
type MessageProposeOutcome struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarketId        []byte                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`                       // 20 bytes
	ResolverAddress []byte                 `protobuf:"bytes,2,opt,name=resolver_address,json=resolverAddress,proto3" json:"resolver_address,omitempty"`  // 20 bytes
	ProposedOutcome bool                   `protobuf:"varint,3,opt,name=proposed_outcome,json=proposedOutcome,proto3" json:"proposed_outcome,omitempty"` // true = YES, false = NO
	ProposalBond    uint64                 `protobuf:"varint,4,opt,name=proposal_bond,json=proposalBond,proto3" json:"proposal_bond,omitempty"`          // PRX bond (min computeMinBond(market))
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageProposeOutcome) Reset() {
	*x = MessageProposeOutcome{}
	mi := &file_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageProposeOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageProposeOutcome) ProtoMessage() {}

func (x *MessageProposeOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageProposeOutcome.ProtoReflect.Descriptor instead.
func (*MessageProposeOutcome) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{9}
}

func (x *MessageProposeOutcome) GetMarketId() []byte {
	if x != nil {
		return x.MarketId
	}
	return nil
}

func (x *MessageProposeOutcome) GetResolverAddress() []byte {
	if x != nil {
		return x.ResolverAddress
	}
	return nil
}

func (x *MessageProposeOutcome) GetProposedOutcome() bool {
	if x != nil {
		return x.ProposedOutcome
	}
	return false
}

func (x *MessageProposeOutcome) GetProposalBond() uint64 {
	if x != nil {
		return x.ProposalBond
	}
	return 0
}

// file_dispute — index 7
type MessageFileDispute struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarketId        []byte                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`                      // 20 bytes
	DisputerAddress []byte                 `protobuf:"bytes,2,opt,name=disputer_address,json=disputerAddress,proto3" json:"disputer_address,omitempty"` // 20 bytes
	DisputeBond     uint64                 `protobuf:"varint,3,opt,name=dispute_bond,json=disputeBond,proto3" json:"dispute_bond,omitempty"`            // PRX bond
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageFileDispute) Reset() {
	*x = MessageFileDispute{}
	mi := &file_tx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageFileDispute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFileDispute) ProtoMessage() {}

func (x *MessageFileDispute) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFileDispute.ProtoReflect.Descriptor instead.
func (*MessageFileDispute) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{10}
}

func (x *MessageFileDispute) GetMarketId() []byte {
	if x != nil {
		return x.MarketId
	}
	return nil
}

func (x *MessageFileDispute) GetDisputerAddress() []byte {
	if x != nil {
		return x.DisputerAddress
	}
	return nil
}

func (x *MessageFileDispute) GetDisputeBond() uint64 {
	if x != nil {
		return x.DisputeBond
	}
	return 0
}

// commit_vote — index 8
// Commit phase: SHA256(vote || nonce || addr)
type MessageCommitVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      []byte                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`       // 20 bytes
	VoterAddr     []byte                 `protobuf:"bytes,2,opt,name=voter_addr,json=voterAddr,proto3" json:"voter_addr,omitempty"`    // 20 bytes
	CommitHash    []byte                 `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"` // 32-byte SHA256 commitment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCommitVote) Reset() {
	*x = MessageCommitVote{}
	mi := &file_tx_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCommitVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCommitVote) ProtoMessage() {}

func (x *MessageCommitVote) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCommitVote.ProtoReflect.Descriptor instead.
func (*MessageCommitVote) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{11}
}

func (x *MessageCommitVote) GetMarketId() []byte {
	if x != nil {
		return x.MarketId
	}
	return nil
}

func (x *MessageCommitVote) GetVoterAddr() []byte {
	if x != nil {
		return x.VoterAddr
	}
	return nil
}

func (x *MessageCommitVote) GetCommitHash() []byte {
	if x != nil {
		return x.CommitHash
	}
	return nil
}

// reveal_vote — index 9
type MessageRevealVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      []byte                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`    // 20 bytes
	VoterAddr     []byte                 `protobuf:"bytes,2,opt,name=voter_addr,json=voterAddr,proto3" json:"voter_addr,omitempty"` // 20 bytes
	Vote          bool                   `protobuf:"varint,3,opt,name=vote,proto3" json:"vote,omitempty"`                           // true = YES, false = NO
	Nonce         []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`                          // reveal nonce — DeliverTx recomputes hash to verify
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRevealVote) Reset() {
	*x = MessageRevealVote{}
	mi := &file_tx_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRevealVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRevealVote) ProtoMessage() {}

func (x *MessageRevealVote) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRevealVote.ProtoReflect.Descriptor instead.
func (*MessageRevealVote) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{12}
}

func (x *MessageRevealVote) GetMarketId() []byte {
	if x != nil {
		return x.MarketId
	}
	return nil
}

func (x *MessageRevealVote) GetVoterAddr() []byte {
	if x != nil {
		return x.VoterAddr
	}
	return nil
}

func (x *MessageRevealVote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

func (x *MessageRevealVote) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// tally_votes — index 10
// NF-1 fix: was missing from ContractConfig and proto entirely.
// Permissionless — no AuthorizedSigners restriction.
type MessageTallyVotes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      []byte                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`       // 20 bytes
	CallerAddr    []byte                 `protobuf:"bytes,2,opt,name=caller_addr,json=callerAddr,proto3" json:"caller_addr,omitempty"` // 20 bytes — caller (receives no reward; permissionless trigger)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageTallyVotes) Reset() {
	*x = MessageTallyVotes{}
	mi := &file_tx_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTallyVotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTallyVotes) ProtoMessage() {}

func (x *MessageTallyVotes) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTallyVotes.ProtoReflect.Descriptor instead.
func (*MessageTallyVotes) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{13}
}

func (x *MessageTallyVotes) GetMarketId() []byte {
	if x != nil {
		return x.MarketId
	}
	return nil
}

func (x *MessageTallyVotes) GetCallerAddr() []byte {
	if x != nil {
		return x.CallerAddr
	}
	return nil
}

// finalize_market — index 11
// Permissionless finalization; caller receives 50 PRX bounty from 0x14 TreasuryReserve.
type MessageFinalizeMarket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      []byte                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`       // 20 bytes
	CallerAddr    []byte                 `protobuf:"bytes,2,opt,name=caller_addr,json=callerAddr,proto3" json:"caller_addr,omitempty"` // 20 bytes — receives the 50 PRX finalization bounty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageFinalizeMarket) Reset() {
	*x = MessageFinalizeMarket{}
	mi := &file_tx_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageFinalizeMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageFinalizeMarket) ProtoMessage() {}

func (x *MessageFinalizeMarket) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageFinalizeMarket.ProtoReflect.Descriptor instead.
func (*MessageFinalizeMarket) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{14}
}

func (x *MessageFinalizeMarket) GetMarketId() []byte {
	if x != nil {
		return x.MarketId
	}
	return nil
}

func (x *MessageFinalizeMarket) GetCallerAddr() []byte {
	if x != nil {
		return x.CallerAddr
	}
	return nil
}

// claim_slash — index 12 (combined plugin has 12 types including send)
// Wait: per PORS spec the combined plugin has send(0)+4 ADLMSR(1-4)+8 PORS(5-11) = 13.
// Per PORS NF-1 fix the combined plugin has exactly 12 types (send + 11 Praxis).
// claim_slash is index 11, finalize_market removed per spec reconciliation below:
// PORS spec §ContractConfig lists: register_resolver, propose_outcome, file_dispute,
// commit_vote, reveal_vote, tally_votes, finalize_market, claim_slash = 8 PORS types.
// With send + 4 ADLMSR = 5, combined = 13. But PORS NF-1 explicitly says "12 types".
// Resolution: claim_slash = index 11, finalize_market = index 10 (tally leads to finalize),
// tally_votes = index 9. Combined = send(0)+create(1)+submit(2)+resolve(3)+claim(4)+
// register(5)+propose(6)+dispute(7)+commit(8)+reveal(9)+tally(10)+finalize_market(11) = 12.
// claim_slash moved to separate invocation or merged — follow whichever your repo uses.
// For now we define it; adjust ContractConfig indices to match.
type MessageClaimSlash struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarketId        []byte                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`                      // 20 bytes
	ClaimantAddress []byte                 `protobuf:"bytes,2,opt,name=claimant_address,json=claimantAddress,proto3" json:"claimant_address,omitempty"` // 20 bytes — resolver or disputer claiming slash proceeds
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageClaimSlash) Reset() {
	*x = MessageClaimSlash{}
	mi := &file_tx_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageClaimSlash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageClaimSlash) ProtoMessage() {}

func (x *MessageClaimSlash) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageClaimSlash.ProtoReflect.Descriptor instead.
func (*MessageClaimSlash) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{15}
}

func (x *MessageClaimSlash) GetMarketId() []byte {
	if x != nil {
		return x.MarketId
	}
	return nil
}

func (x *MessageClaimSlash) GetClaimantAddress() []byte {
	if x != nil {
		return x.ClaimantAddress
	}
	return nil
}

// ═══════════════════════════════════════════════════════════════════════════
// STATE MESSAGES — stored in Praxis state (0x10–0x1C)
// These are persisted via StateWrite, never sent as transactions.
// ═══════════════════════════════════════════════════════════════════════════
// 0x10 — MarketState (per market_id)
// CRIT-1: field names are proto-generated — QYes, QNo, BEff, ElevatedRisk, etc.
type MarketState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`                                       // see STATUS_ constants
	ExpiryTime     uint64                 `protobuf:"varint,2,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"`             // block height
	QYes           uint64                 `protobuf:"varint,3,opt,name=q_yes,json=qYes,proto3" json:"q_yes,omitempty"`                               // LMSR YES quantity (Go: QYes)
	QNo            uint64                 `protobuf:"varint,4,opt,name=q_no,json=qNo,proto3" json:"q_no,omitempty"`                                  // LMSR NO quantity (Go: QNo)
	BEff           uint64                 `protobuf:"varint,5,opt,name=b_eff,json=bEff,proto3" json:"b_eff,omitempty"`                               // effective liquidity parameter (Go: BEff)
	Creator        []byte                 `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`                                      // 20 bytes creator address
	ClaimedCount   uint64                 `protobuf:"varint,7,opt,name=claimed_count,json=claimedCount,proto3" json:"claimed_count,omitempty"`       // (Go: ClaimedCount)
	TotalPositions uint64                 `protobuf:"varint,8,opt,name=total_positions,json=totalPositions,proto3" json:"total_positions,omitempty"` // (Go: TotalPositions)
	OpenTime       uint64                 `protobuf:"varint,9,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`                   // block height when market opened (Go: OpenTime)
	ElevatedRisk   bool                   `protobuf:"varint,10,opt,name=elevated_risk,json=elevatedRisk,proto3" json:"elevated_risk,omitempty"`      // NF-4 fix: field 10, not placeholder N (Go: ElevatedRisk)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarketState) Reset() {
	*x = MarketState{}
	mi := &file_tx_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketState) ProtoMessage() {}

func (x *MarketState) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketState.ProtoReflect.Descriptor instead.
func (*MarketState) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{16}
}

func (x *MarketState) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MarketState) GetExpiryTime() uint64 {
	if x != nil {
		return x.ExpiryTime
	}
	return 0
}

func (x *MarketState) GetQYes() uint64 {
	if x != nil {
		return x.QYes
	}
	return 0
}

func (x *MarketState) GetQNo() uint64 {
	if x != nil {
		return x.QNo
	}
	return 0
}

func (x *MarketState) GetBEff() uint64 {
	if x != nil {
		return x.BEff
	}
	return 0
}

func (x *MarketState) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *MarketState) GetClaimedCount() uint64 {
	if x != nil {
		return x.ClaimedCount
	}
	return 0
}

func (x *MarketState) GetTotalPositions() uint64 {
	if x != nil {
		return x.TotalPositions
	}
	return 0
}

func (x *MarketState) GetOpenTime() uint64 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

func (x *MarketState) GetElevatedRisk() bool {
	if x != nil {
		return x.ElevatedRisk
	}
	return false
}

// 0x11 — PositionState (per market_id + claimant_address)
// CRIT-1: SharesYes, SharesNo — never SharesYES/SharesNO or ForecasterAddress/Outcome/Amount
type PositionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharesYes     uint64                 `protobuf:"varint,1,opt,name=shares_yes,json=sharesYes,proto3" json:"shares_yes,omitempty"` // (Go: SharesYes)
	SharesNo      uint64                 `protobuf:"varint,2,opt,name=shares_no,json=sharesNo,proto3" json:"shares_no,omitempty"`    // (Go: SharesNo)
	CostPaid      uint64                 `protobuf:"varint,3,opt,name=cost_paid,json=costPaid,proto3" json:"cost_paid,omitempty"`    // total PRX paid for this position (Go: CostPaid)
	Claimed       bool                   `protobuf:"varint,4,opt,name=claimed,proto3" json:"claimed,omitempty"`                      // (Go: Claimed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionState) Reset() {
	*x = PositionState{}
	mi := &file_tx_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionState) ProtoMessage() {}

func (x *PositionState) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionState.ProtoReflect.Descriptor instead.
func (*PositionState) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{17}
}

func (x *PositionState) GetSharesYes() uint64 {
	if x != nil {
		return x.SharesYes
	}
	return 0
}

func (x *PositionState) GetSharesNo() uint64 {
	if x != nil {
		return x.SharesNo
	}
	return 0
}

func (x *PositionState) GetCostPaid() uint64 {
	if x != nil {
		return x.CostPaid
	}
	return 0
}

func (x *PositionState) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

// 0x12 — OutcomeState (per market_id) — idempotency sentinel for ResolveMarket
type OutcomeState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WinningOutcome bool                   `protobuf:"varint,1,opt,name=winning_outcome,json=winningOutcome,proto3" json:"winning_outcome,omitempty"`
	ResolvedAt     uint64                 `protobuf:"varint,2,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"` // block height
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutcomeState) Reset() {
	*x = OutcomeState{}
	mi := &file_tx_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutcomeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutcomeState) ProtoMessage() {}

func (x *OutcomeState) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutcomeState.ProtoReflect.Descriptor instead.
func (*OutcomeState) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{18}
}

func (x *OutcomeState) GetWinningOutcome() bool {
	if x != nil {
		return x.WinningOutcome
	}
	return false
}

func (x *OutcomeState) GetResolvedAt() uint64 {
	if x != nil {
		return x.ResolvedAt
	}
	return 0
}

// 0x13 — ResolverState (per market_id) — written by propose_outcome as 4th atomic key (NF-5)
type ResolverState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResolverAddress []byte                 `protobuf:"bytes,1,opt,name=resolver_address,json=resolverAddress,proto3" json:"resolver_address,omitempty"` // 20 bytes
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolverState) Reset() {
	*x = ResolverState{}
	mi := &file_tx_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolverState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolverState) ProtoMessage() {}

func (x *ResolverState) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolverState.ProtoReflect.Descriptor instead.
func (*ResolverState) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{19}
}

func (x *ResolverState) GetResolverAddress() []byte {
	if x != nil {
		return x.ResolverAddress
	}
	return nil
}

// 0x14 — TreasuryReserve (per market_id)
type TreasuryReserve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockedReserve uint64                 `protobuf:"varint,1,opt,name=locked_reserve,json=lockedReserve,proto3" json:"locked_reserve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreasuryReserve) Reset() {
	*x = TreasuryReserve{}
	mi := &file_tx_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreasuryReserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreasuryReserve) ProtoMessage() {}

func (x *TreasuryReserve) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreasuryReserve.ProtoReflect.Descriptor instead.
func (*TreasuryReserve) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{20}
}

func (x *TreasuryReserve) GetLockedReserve() uint64 {
	if x != nil {
		return x.LockedReserve
	}
	return 0
}

// 0x16 — ResolverRecord (global, per resolver_address)
type ResolverRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResolverAddress []byte                 `protobuf:"bytes,1,opt,name=resolver_address,json=resolverAddress,proto3" json:"resolver_address,omitempty"`
	StakeAmount     uint64                 `protobuf:"varint,2,opt,name=stake_amount,json=stakeAmount,proto3" json:"stake_amount,omitempty"`
	RrsScore        uint64                 `protobuf:"varint,3,opt,name=rrs_score,json=rrsScore,proto3" json:"rrs_score,omitempty"`
	RegisteredAt    uint64                 `protobuf:"varint,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolverRecord) Reset() {
	*x = ResolverRecord{}
	mi := &file_tx_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolverRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolverRecord) ProtoMessage() {}

func (x *ResolverRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolverRecord.ProtoReflect.Descriptor instead.
func (*ResolverRecord) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{21}
}

func (x *ResolverRecord) GetResolverAddress() []byte {
	if x != nil {
		return x.ResolverAddress
	}
	return nil
}

func (x *ResolverRecord) GetStakeAmount() uint64 {
	if x != nil {
		return x.StakeAmount
	}
	return 0
}

func (x *ResolverRecord) GetRrsScore() uint64 {
	if x != nil {
		return x.RrsScore
	}
	return 0
}

func (x *ResolverRecord) GetRegisteredAt() uint64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

// 0x17 — ProposalRecord (per market_id)
type ProposalRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResolverAddr    []byte                 `protobuf:"bytes,1,opt,name=resolver_addr,json=resolverAddr,proto3" json:"resolver_addr,omitempty"`
	ProposedOutcome bool                   `protobuf:"varint,2,opt,name=proposed_outcome,json=proposedOutcome,proto3" json:"proposed_outcome,omitempty"`
	ProposalBond    uint64                 `protobuf:"varint,3,opt,name=proposal_bond,json=proposalBond,proto3" json:"proposal_bond,omitempty"`
	ProposalBlock   uint64                 `protobuf:"varint,4,opt,name=proposal_block,json=proposalBlock,proto3" json:"proposal_block,omitempty"`
	Status          uint32                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // PROPOSAL_OPEN, PROPOSAL_ACCEPTED, PROPOSAL_SLASHED
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProposalRecord) Reset() {
	*x = ProposalRecord{}
	mi := &file_tx_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalRecord) ProtoMessage() {}

func (x *ProposalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalRecord.ProtoReflect.Descriptor instead.
func (*ProposalRecord) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{22}
}

func (x *ProposalRecord) GetResolverAddr() []byte {
	if x != nil {
		return x.ResolverAddr
	}
	return nil
}

func (x *ProposalRecord) GetProposedOutcome() bool {
	if x != nil {
		return x.ProposedOutcome
	}
	return false
}

func (x *ProposalRecord) GetProposalBond() uint64 {
	if x != nil {
		return x.ProposalBond
	}
	return 0
}

func (x *ProposalRecord) GetProposalBlock() uint64 {
	if x != nil {
		return x.ProposalBlock
	}
	return 0
}

func (x *ProposalRecord) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 0x18 — DisputeRecord (per market_id)
type DisputeRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DisputerAddress []byte                 `protobuf:"bytes,1,opt,name=disputer_address,json=disputerAddress,proto3" json:"disputer_address,omitempty"`
	DisputeBond     uint64                 `protobuf:"varint,2,opt,name=dispute_bond,json=disputeBond,proto3" json:"dispute_bond,omitempty"`
	DisputeBlock    uint64                 `protobuf:"varint,3,opt,name=dispute_block,json=disputeBlock,proto3" json:"dispute_block,omitempty"`
	VoteStatus      uint32                 `protobuf:"varint,4,opt,name=vote_status,json=voteStatus,proto3" json:"vote_status,omitempty"`
	PanelSize       uint32                 `protobuf:"varint,5,opt,name=panel_size,json=panelSize,proto3" json:"panel_size,omitempty"`
	PanelMembers    [][]byte               `protobuf:"bytes,6,rep,name=panel_members,json=panelMembers,proto3" json:"panel_members,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DisputeRecord) Reset() {
	*x = DisputeRecord{}
	mi := &file_tx_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisputeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisputeRecord) ProtoMessage() {}

func (x *DisputeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisputeRecord.ProtoReflect.Descriptor instead.
func (*DisputeRecord) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{23}
}

func (x *DisputeRecord) GetDisputerAddress() []byte {
	if x != nil {
		return x.DisputerAddress
	}
	return nil
}

func (x *DisputeRecord) GetDisputeBond() uint64 {
	if x != nil {
		return x.DisputeBond
	}
	return 0
}

func (x *DisputeRecord) GetDisputeBlock() uint64 {
	if x != nil {
		return x.DisputeBlock
	}
	return 0
}

func (x *DisputeRecord) GetVoteStatus() uint32 {
	if x != nil {
		return x.VoteStatus
	}
	return 0
}

func (x *DisputeRecord) GetPanelSize() uint32 {
	if x != nil {
		return x.PanelSize
	}
	return 0
}

func (x *DisputeRecord) GetPanelMembers() [][]byte {
	if x != nil {
		return x.PanelMembers
	}
	return nil
}

// 0x19 — VoteCommit (per market_id + voter_addr)
type VoteCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoterAddr     []byte                 `protobuf:"bytes,1,opt,name=voter_addr,json=voterAddr,proto3" json:"voter_addr,omitempty"`
	CommitHash    []byte                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	CommittedAt   uint64                 `protobuf:"varint,3,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteCommit) Reset() {
	*x = VoteCommit{}
	mi := &file_tx_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteCommit) ProtoMessage() {}

func (x *VoteCommit) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteCommit.ProtoReflect.Descriptor instead.
func (*VoteCommit) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{24}
}

func (x *VoteCommit) GetVoterAddr() []byte {
	if x != nil {
		return x.VoterAddr
	}
	return nil
}

func (x *VoteCommit) GetCommitHash() []byte {
	if x != nil {
		return x.CommitHash
	}
	return nil
}

func (x *VoteCommit) GetCommittedAt() uint64 {
	if x != nil {
		return x.CommittedAt
	}
	return 0
}

// 0x1A — VoteReveal (per market_id + voter_addr)
type VoteReveal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoterAddr     []byte                 `protobuf:"bytes,1,opt,name=voter_addr,json=voterAddr,proto3" json:"voter_addr,omitempty"`
	Vote          bool                   `protobuf:"varint,2,opt,name=vote,proto3" json:"vote,omitempty"`
	RevealedAt    uint64                 `protobuf:"varint,3,opt,name=revealed_at,json=revealedAt,proto3" json:"revealed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteReveal) Reset() {
	*x = VoteReveal{}
	mi := &file_tx_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteReveal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteReveal) ProtoMessage() {}

func (x *VoteReveal) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteReveal.ProtoReflect.Descriptor instead.
func (*VoteReveal) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{25}
}

func (x *VoteReveal) GetVoterAddr() []byte {
	if x != nil {
		return x.VoterAddr
	}
	return nil
}

func (x *VoteReveal) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

func (x *VoteReveal) GetRevealedAt() uint64 {
	if x != nil {
		return x.RevealedAt
	}
	return 0
}

// 0x1B — SlashRecord (per resolver_address)
type SlashRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SlashedAddress []byte                 `protobuf:"bytes,1,opt,name=slashed_address,json=slashedAddress,proto3" json:"slashed_address,omitempty"`
	SlashAmount    uint64                 `protobuf:"varint,2,opt,name=slash_amount,json=slashAmount,proto3" json:"slash_amount,omitempty"`
	SlashedAt      uint64                 `protobuf:"varint,3,opt,name=slashed_at,json=slashedAt,proto3" json:"slashed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SlashRecord) Reset() {
	*x = SlashRecord{}
	mi := &file_tx_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlashRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlashRecord) ProtoMessage() {}

func (x *SlashRecord) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlashRecord.ProtoReflect.Descriptor instead.
func (*SlashRecord) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{26}
}

func (x *SlashRecord) GetSlashedAddress() []byte {
	if x != nil {
		return x.SlashedAddress
	}
	return nil
}

func (x *SlashRecord) GetSlashAmount() uint64 {
	if x != nil {
		return x.SlashAmount
	}
	return 0
}

func (x *SlashRecord) GetSlashedAt() uint64 {
	if x != nil {
		return x.SlashedAt
	}
	return 0
}

// 0x1C — PanelEntropyAccum (singleton rolling entropy accumulator)
type PanelEntropyAccum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accumulator   uint64                 `protobuf:"varint,1,opt,name=accumulator,proto3" json:"accumulator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelEntropyAccum) Reset() {
	*x = PanelEntropyAccum{}
	mi := &file_tx_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelEntropyAccum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelEntropyAccum) ProtoMessage() {}

func (x *PanelEntropyAccum) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelEntropyAccum.ProtoReflect.Descriptor instead.
func (*PanelEntropyAccum) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{27}
}

func (x *PanelEntropyAccum) GetAccumulator() uint64 {
	if x != nil {
		return x.Accumulator
	}
	return 0
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"H\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xa3\x02\n" +
	"\vTransaction\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12&\n" +
	"\x03msg\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03msg\x12.\n" +
	"\tsignature\x18\x03 \x01(\v2\x10.types.SignatureR\tsignature\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x04R\x03fee\x12\x12\n" +
	"\x04memo\x18\a \x01(\tR\x04memo\x12\x1d\n" +
	"\n" +
	"network_id\x18\b \x01(\x04R\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\"\xe2\x01\n" +
	"\tFeeParams\x12\x19\n" +
	"\bsend_fee\x18\x01 \x01(\x04R\asendFee\x12*\n" +
	"\x11create_market_fee\x18\x02 \x01(\x04R\x0fcreateMarketFee\x122\n" +
	"\x15submit_prediction_fee\x18\x03 \x01(\x04R\x13submitPredictionFee\x12,\n" +
	"\x12resolve_market_fee\x18\x04 \x01(\x04R\x10resolveMarketFee\x12,\n" +
	"\x12claim_winnings_fee\x18\x05 \x01(\x04R\x10claimWinningsFee\"g\n" +
	"\vMessageSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\fR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\fR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"\xa1\x01\n" +
	"\x13MessageCreateMarket\x12'\n" +
	"\x0fcreator_address\x18\x01 \x01(\fR\x0ecreatorAddress\x12\x0e\n" +
	"\x02b0\x18\x02 \x01(\x04R\x02b0\x12\x1f\n" +
	"\vexpiry_time\x18\x03 \x01(\x04R\n" +
	"expiryTime\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\x12\x1a\n" +
	"\bquestion\x18\x05 \x01(\tR\bquestion\"\xaa\x01\n" +
	"\x17MessageSubmitPrediction\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\fR\bmarketId\x12%\n" +
	"\x0ebettor_address\x18\x02 \x01(\fR\rbettorAddress\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\bR\aoutcome\x12\x16\n" +
	"\x06shares\x18\x04 \x01(\x04R\x06shares\x12\x19\n" +
	"\bmax_cost\x18\x05 \x01(\x04R\amaxCost\"\x87\x01\n" +
	"\x14MessageResolveMarket\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\fR\bmarketId\x12)\n" +
	"\x10resolver_address\x18\x02 \x01(\fR\x0fresolverAddress\x12'\n" +
	"\x0fwinning_outcome\x18\x03 \x01(\bR\x0ewinningOutcome\"^\n" +
	"\x14MessageClaimWinnings\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\fR\bmarketId\x12)\n" +
	"\x10claimant_address\x18\x02 \x01(\fR\x0fclaimantAddress\"g\n" +
	"\x17MessageRegisterResolver\x12)\n" +
	"\x10resolver_address\x18\x01 \x01(\fR\x0fresolverAddress\x12!\n" +
	"\fstake_amount\x18\x02 \x01(\x04R\vstakeAmount\"\xaf\x01\n" +
	"\x15MessageProposeOutcome\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\fR\bmarketId\x12)\n" +
	"\x10resolver_address\x18\x02 \x01(\fR\x0fresolverAddress\x12)\n" +
	"\x10proposed_outcome\x18\x03 \x01(\bR\x0fproposedOutcome\x12#\n" +
	"\rproposal_bond\x18\x04 \x01(\x04R\fproposalBond\"\x7f\n" +
	"\x12MessageFileDispute\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\fR\bmarketId\x12)\n" +
	"\x10disputer_address\x18\x02 \x01(\fR\x0fdisputerAddress\x12!\n" +
	"\fdispute_bond\x18\x03 \x01(\x04R\vdisputeBond\"p\n" +
	"\x11MessageCommitVote\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\fR\bmarketId\x12\x1d\n" +
	"\n" +
	"voter_addr\x18\x02 \x01(\fR\tvoterAddr\x12\x1f\n" +
	"\vcommit_hash\x18\x03 \x01(\fR\n" +
	"commitHash\"y\n" +
	"\x11MessageRevealVote\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\fR\bmarketId\x12\x1d\n" +
	"\n" +
	"voter_addr\x18\x02 \x01(\fR\tvoterAddr\x12\x12\n" +
	"\x04vote\x18\x03 \x01(\bR\x04vote\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\"Q\n" +
	"\x11MessageTallyVotes\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\fR\bmarketId\x12\x1f\n" +
	"\vcaller_addr\x18\x02 \x01(\fR\n" +
	"callerAddr\"U\n" +
	"\x15MessageFinalizeMarket\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\fR\bmarketId\x12\x1f\n" +
	"\vcaller_addr\x18\x02 \x01(\fR\n" +
	"callerAddr\"[\n" +
	"\x11MessageClaimSlash\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\fR\bmarketId\x12)\n" +
	"\x10claimant_address\x18\x02 \x01(\fR\x0fclaimantAddress\"\xad\x02\n" +
	"\vMarketState\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12\x1f\n" +
	"\vexpiry_time\x18\x02 \x01(\x04R\n" +
	"expiryTime\x12\x13\n" +
	"\x05q_yes\x18\x03 \x01(\x04R\x04qYes\x12\x11\n" +
	"\x04q_no\x18\x04 \x01(\x04R\x03qNo\x12\x13\n" +
	"\x05b_eff\x18\x05 \x01(\x04R\x04bEff\x12\x18\n" +
	"\acreator\x18\x06 \x01(\fR\acreator\x12#\n" +
	"\rclaimed_count\x18\a \x01(\x04R\fclaimedCount\x12'\n" +
	"\x0ftotal_positions\x18\b \x01(\x04R\x0etotalPositions\x12\x1b\n" +
	"\topen_time\x18\t \x01(\x04R\bopenTime\x12#\n" +
	"\relevated_risk\x18\n" +
	" \x01(\bR\felevatedRisk\"\x82\x01\n" +
	"\rPositionState\x12\x1d\n" +
	"\n" +
	"shares_yes\x18\x01 \x01(\x04R\tsharesYes\x12\x1b\n" +
	"\tshares_no\x18\x02 \x01(\x04R\bsharesNo\x12\x1b\n" +
	"\tcost_paid\x18\x03 \x01(\x04R\bcostPaid\x12\x18\n" +
	"\aclaimed\x18\x04 \x01(\bR\aclaimed\"X\n" +
	"\fOutcomeState\x12'\n" +
	"\x0fwinning_outcome\x18\x01 \x01(\bR\x0ewinningOutcome\x12\x1f\n" +
	"\vresolved_at\x18\x02 \x01(\x04R\n" +
	"resolvedAt\":\n" +
	"\rResolverState\x12)\n" +
	"\x10resolver_address\x18\x01 \x01(\fR\x0fresolverAddress\"8\n" +
	"\x0fTreasuryReserve\x12%\n" +
	"\x0elocked_reserve\x18\x01 \x01(\x04R\rlockedReserve\"\xa0\x01\n" +
	"\x0eResolverRecord\x12)\n" +
	"\x10resolver_address\x18\x01 \x01(\fR\x0fresolverAddress\x12!\n" +
	"\fstake_amount\x18\x02 \x01(\x04R\vstakeAmount\x12\x1b\n" +
	"\trrs_score\x18\x03 \x01(\x04R\brrsScore\x12#\n" +
	"\rregistered_at\x18\x04 \x01(\x04R\fregisteredAt\"\xc4\x01\n" +
	"\x0eProposalRecord\x12#\n" +
	"\rresolver_addr\x18\x01 \x01(\fR\fresolverAddr\x12)\n" +
	"\x10proposed_outcome\x18\x02 \x01(\bR\x0fproposedOutcome\x12#\n" +
	"\rproposal_bond\x18\x03 \x01(\x04R\fproposalBond\x12%\n" +
	"\x0eproposal_block\x18\x04 \x01(\x04R\rproposalBlock\x12\x16\n" +
	"\x06status\x18\x05 \x01(\rR\x06status\"\xe7\x01\n" +
	"\rDisputeRecord\x12)\n" +
	"\x10disputer_address\x18\x01 \x01(\fR\x0fdisputerAddress\x12!\n" +
	"\fdispute_bond\x18\x02 \x01(\x04R\vdisputeBond\x12#\n" +
	"\rdispute_block\x18\x03 \x01(\x04R\fdisputeBlock\x12\x1f\n" +
	"\vvote_status\x18\x04 \x01(\rR\n" +
	"voteStatus\x12\x1d\n" +
	"\n" +
	"panel_size\x18\x05 \x01(\rR\tpanelSize\x12#\n" +
	"\rpanel_members\x18\x06 \x03(\fR\fpanelMembers\"o\n" +
	"\n" +
	"VoteCommit\x12\x1d\n" +
	"\n" +
	"voter_addr\x18\x01 \x01(\fR\tvoterAddr\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\fR\n" +
	"commitHash\x12!\n" +
	"\fcommitted_at\x18\x03 \x01(\x04R\vcommittedAt\"`\n" +
	"\n" +
	"VoteReveal\x12\x1d\n" +
	"\n" +
	"voter_addr\x18\x01 \x01(\fR\tvoterAddr\x12\x12\n" +
	"\x04vote\x18\x02 \x01(\bR\x04vote\x12\x1f\n" +
	"\vrevealed_at\x18\x03 \x01(\x04R\n" +
	"revealedAt\"x\n" +
	"\vSlashRecord\x12'\n" +
	"\x0fslashed_address\x18\x01 \x01(\fR\x0eslashedAddress\x12!\n" +
	"\fslash_amount\x18\x02 \x01(\x04R\vslashAmount\x12\x1d\n" +
	"\n" +
	"slashed_at\x18\x03 \x01(\x04R\tslashedAt\"5\n" +
	"\x11PanelEntropyAccum\x12 \n" +
	"\vaccumulator\x18\x01 \x01(\x04R\vaccumulatorB5Z3github.com/canopy-network/canopy/plugin/go/contractb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_tx_proto_goTypes = []any{
	(*Signature)(nil),               // 0: types.Signature
	(*Transaction)(nil),             // 1: types.Transaction
	(*FeeParams)(nil),               // 2: types.FeeParams
	(*MessageSend)(nil),             // 3: types.MessageSend
	(*MessageCreateMarket)(nil),     // 4: types.MessageCreateMarket
	(*MessageSubmitPrediction)(nil), // 5: types.MessageSubmitPrediction
	(*MessageResolveMarket)(nil),    // 6: types.MessageResolveMarket
	(*MessageClaimWinnings)(nil),    // 7: types.MessageClaimWinnings
	(*MessageRegisterResolver)(nil), // 8: types.MessageRegisterResolver
	(*MessageProposeOutcome)(nil),   // 9: types.MessageProposeOutcome
	(*MessageFileDispute)(nil),      // 10: types.MessageFileDispute
	(*MessageCommitVote)(nil),       // 11: types.MessageCommitVote
	(*MessageRevealVote)(nil),       // 12: types.MessageRevealVote
	(*MessageTallyVotes)(nil),       // 13: types.MessageTallyVotes
	(*MessageFinalizeMarket)(nil),   // 14: types.MessageFinalizeMarket
	(*MessageClaimSlash)(nil),       // 15: types.MessageClaimSlash
	(*MarketState)(nil),             // 16: types.MarketState
	(*PositionState)(nil),           // 17: types.PositionState
	(*OutcomeState)(nil),            // 18: types.OutcomeState
	(*ResolverState)(nil),           // 19: types.ResolverState
	(*TreasuryReserve)(nil),         // 20: types.TreasuryReserve
	(*ResolverRecord)(nil),          // 21: types.ResolverRecord
	(*ProposalRecord)(nil),          // 22: types.ProposalRecord
	(*DisputeRecord)(nil),           // 23: types.DisputeRecord
	(*VoteCommit)(nil),              // 24: types.VoteCommit
	(*VoteReveal)(nil),              // 25: types.VoteReveal
	(*SlashRecord)(nil),             // 26: types.SlashRecord
	(*PanelEntropyAccum)(nil),       // 27: types.PanelEntropyAccum
	(*any1.Any)(nil),                // 28: google.protobuf.Any
}
var file_tx_proto_depIdxs = []int32{
	28, // 0: types.Transaction.msg:type_name -> google.protobuf.Any
	0,  // 1: types.Transaction.signature:type_name -> types.Signature
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
