package contract

// tx_shim.go — bridges old symbol names (expected by plugin.pb.go and
// z_descriptor.go) to the new names generated by protoc from proto/tx.proto.

import "google.golang.org/protobuf/reflect/protoreflect"

var File_tx_proto protoreflect.FileDescriptor

func file_tx_proto_init() {
file_proto_tx_proto_init()
File_tx_proto = File_proto_tx_proto
}
