// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: validator.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Validator mirrors Canopy's lib.Validator (lib/.proto/validator.proto:26).
// Plugins decode validator records from the FSM at contract.KeyForValidator()
// to inspect address / staked amount / committees membership without
// re-implementing the validator state machine. Field numbers MUST match the
// FSM's Validator so wire-format unmarshal succeeds; fields we don't need
// (public_key, net_address, max_paused_height, unstaking_height, output,
// delegate, compound) are intentionally omitted — proto3 ignores unknown
// fields during decode.
type Validator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address: the short version of the operator public key.
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// staked_amount: the operator's surety-bonded uCNPY. Field number must
	// be 4 to match lib.Validator.
	StakedAmount uint64 `protobuf:"varint,4,opt,name=staked_amount,json=stakedAmount,proto3" json:"stakedAmount"` // @gotags: json:"stakedAmount"
	// committees: the list of Canopy chain ids whose committees this
	// validator participates in. Restaking gives each listed committee the
	// operator's full staked_amount as exposure. Field number must be 5.
	Committees    []uint64 `protobuf:"varint,5,rep,packed,name=committees,proto3" json:"committees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validator) Reset() {
	*x = Validator{}
	mi := &file_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_validator_proto_rawDescGZIP(), []int{0}
}

func (x *Validator) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Validator) GetStakedAmount() uint64 {
	if x != nil {
		return x.StakedAmount
	}
	return 0
}

func (x *Validator) GetCommittees() []uint64 {
	if x != nil {
		return x.Committees
	}
	return nil
}

var File_validator_proto protoreflect.FileDescriptor

const file_validator_proto_rawDesc = "" +
	"\n" +
	"\x0fvalidator.proto\x12\x05types\"j\n" +
	"\tValidator\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12#\n" +
	"\rstaked_amount\x18\x04 \x01(\x04R\fstakedAmount\x12\x1e\n" +
	"\n" +
	"committees\x18\x05 \x03(\x04R\n" +
	"committeesB.Z,github.com/canopy-network/go-plugin/contractb\x06proto3"

var (
	file_validator_proto_rawDescOnce sync.Once
	file_validator_proto_rawDescData []byte
)

func file_validator_proto_rawDescGZIP() []byte {
	file_validator_proto_rawDescOnce.Do(func() {
		file_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validator_proto_rawDesc), len(file_validator_proto_rawDesc)))
	})
	return file_validator_proto_rawDescData
}

var file_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_validator_proto_goTypes = []any{
	(*Validator)(nil), // 0: types.Validator
}
var file_validator_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_validator_proto_init() }
func file_validator_proto_init() {
	if File_validator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validator_proto_rawDesc), len(file_validator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_validator_proto_goTypes,
		DependencyIndexes: file_validator_proto_depIdxs,
		MessageInfos:      file_validator_proto_msgTypes,
	}.Build()
	File_validator_proto = out.File
	file_validator_proto_goTypes = nil
	file_validator_proto_depIdxs = nil
}
